### ISSUE TITLE
Error fetching url [hentai-cafe]

### ISSUE THREAD

**Issue by DukeValentine** [RipMeApp/ripme#1083]
* Ripme version: 1.7.70
* Java version:  1.8.0_161
* Operating system:  Linux Ubuntu
* Exact URL you were trying to rip when the problem occurred: https://hentai.cafe/chobipero-club/

I have tried on 2 different machines (a vps and my desktop) and got the same error.

## Expected Behavior

Ripme downloads all the images in the gallery

## Actual Behavior

```
Retrieving https://hentai.cafe/chobipero-club/
Error while loading https://hentai.cafe/manga/read/chobipero-club/en/0/1/<br />

org.jsoup.HttpStatusException: HTTP error fetching URL. Status=400, URL=https://hentai.cafe/manga/read/chobipero-club/en/0/1/<br%20/>
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.HentaiCafeRipper.getFirstPage(HentaiCafeRipper.java:47)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:86)
        at com.rarchives.ripme.App.rip(App.java:99)
        at com.rarchives.ripme.App.ripURL(App.java:265)
        at com.rarchives.ripme.App.handleArguments(App.java:248)
        at com.rarchives.ripme.App.main(App.java:74)
[!] Error while ripping URL https://hentai.cafe/chobipero-club/
java.io.IOException: Failed to load https://hentai.cafe/manga/read/chobipero-club/en/0/1/<br />
 after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.HentaiCafeRipper.getFirstPage(HentaiCafeRipper.java:47)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:86)
        at com.rarchives.ripme.App.rip(App.java:99)
        at com.rarchives.ripme.App.ripURL(App.java:265)
        at com.rarchives.ripme.App.handleArguments(App.java:248)
        at com.rarchives.ripme.App.main(App.java:74)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=400, URL=https://hentai.cafe/manga/read/chobipero-club/en/0/1/<br%20/>
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 7 more
```

**Comment by cyian-1756** [comment]
> https://hentai.cafe/manga/read/chobipero-club/en/0/1/<br%20/>

I assume the issue here is that the < > isn't url encoded

**Comment by cyian-1756** [comment]
Looks like this is an issue with the site it should link to the comic in the format of /manga/read/NAME/en/0/1/ but in this case links like manga/read/NAME/en/0/1/%3Cbr%20/%3E

I'll start working on a work around
