### ISSUE TITLE
Erome album failing

### ISSUE THREAD

**Issue by cyian-1756** [RipMeApp/ripme#1104]
* Ripme version: 1.7.73
* Java version: 
* Operating system:  Ubuntu 16.04

* Exact URL you were trying to rip when the problem occurred: https://www.erome.com/a/LCv5pYmD
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Rips album

## Actual Behavior

Downloads no images

**Comment by Tush-r** [comment]
This error is caused due to **self signed certificates** or **certificates signed by unknown certificate authority** or **expired certificates**.

This can be solved by:

1. Updating Jsoup in pom.xml and using [validateTLSCertificates(false)](https://jsoup.org/apidocs/org/jsoup/Connection.html#validateTLSCertificates-boolean-) in defaultSettings of Http class.
```
<dependency>
  <!-- jsoup HTML parser library @ https://jsoup.org/ -->
  <groupId>org.jsoup</groupId>
  <artifactId>jsoup</artifactId>
  <version>1.11.3</version>
</dependency>
```

2. Accepting any kind of certificates for https in DownloadFileThread class.
```
TrustManager[] trustAllCerts = new TrustManager[] { new X509TrustManager() {
							public java.security.cert.X509Certificate[] getAcceptedIssuers() {
								return new X509Certificate[0];
							}

							public void checkClientTrusted(java.security.cert.X509Certificate[] certs,
									String authType) {
							}

							public void checkServerTrusted(java.security.cert.X509Certificate[] certs,
									String authType) {
							}
						} };
						SSLContext sc = SSLContext.getInstance("SSL");
						sc.init(null, trustAllCerts, new java.security.SecureRandom());
						((HttpsURLConnection) huc).setSSLSocketFactory(sc.getSocketFactory());
```

Although trusting all certificates is not advised, I've tested this offline and it works.

**Comment by Tush-r** [comment]
> 
> 
> @Tush-r
> 
> > This error is caused due to self signed certificates or certificates signed by unknown certificate authority or expired certificates.
> 
> What makes you assume that? erome has a valid cert from let's encrypt.

Yes I did check the certificate, but a simple run on erome link throws the same exception.

```
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;

public class Test {
	public static void main(String[] args) throws Exception {
		URL url = new URL("https://www.erome.com/a/LCv5pYmD");
		BufferedReader reader = new BufferedReader(new InputStreamReader(url.openStream()));
		String thisLine = null;
		while ((thisLine = reader.readLine()) != null) {
			System.out.println(thisLine);
		}
		reader.close();
	}
}
```
```

Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at Test.main(Test.java:8)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 15 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 21 more
```

**Comment by cyian-1756** [comment]
@Tush-r 

That looks like an issue with your java install no trusting let encrypt certs.

**Comment by Tush-r** [comment]
> 
> 
> @Tush-r
> 
> That looks like an issue with your java install no trusting let encrypt certs.

Yes. It was a mistake on my side. I was using an older JRE.

As for the issue, Erome images are loaded as we scroll through them using javascripts in the code. So none of the images have _src_ attribute and, calling the `element.attr("src")` returns empty string. Therefore the log is spamed with: `Found image url #11: https:           `

This is fixed by a slight change in the `getMediaFromPage(Document doc)` method.
https://github.com/Tush-r/ripme/commit/a2cc83f5615b2d66d6094fc0fac0515bf825a128

There are other 2 issues that I'm still looking into:

- [ ] EromeRipperTest is missing test for image albums, which is why it never flagged the current issue.

- [ ] For video files, EromeRipper downloads both SD and HD files.
