### ISSUE TITLE
Instagram Unable to get query_hash

### ISSUE THREAD

**Issue by t-mart** [RipMeApp/ripme#1107]
* Ripme version: `v1.7.73`
* Java version: `java version "11.0.1"`
* Operating system: `Microsoft Windows [Version 10.0.17134.471]`
* Exact URL you were trying to rip when the problem occurred: [https://www.instagram.com/handmadefont/](https://www.instagram.com/handmadefont/)
* Please include any additional information about how to reproduce the problem:

Straightforward rip of the above url. Ran with command line to capture log output.

## Expected Behavior

Downloads proceed _past_ the first page. Looking at logs, another way of saying this might be "RipMe finds the query_hash".

## Actual Behavior

RipMe will download the first page of Instagram images successfully. Around the end of the first page, you'll see a 403 status code returned. (Not entirely sure how IG ripping working, but seems like, without a valid query_hash, you can't access images as some point.)

This might be the same breakage as:
- https://github.com/RipMeApp/ripme/issues/731

Log here:

```
$ java.exe -jar C:\Users\tim\Desktop\rips\ripme.jar
Loaded C:\Users\tim\AppData\Local\ripme\rip.properties
Loaded log4j.properties
Initialized ripme v1.7.73
Setting locale to default
Loading history from C:\Users\tim\AppData\Local\ripme\history.json
Retrieving https://raw.githubusercontent.com/ripmeapp/ripme/master/ripme.json
This version (1.7.73) is the same or newer than the website's version (1.7.73)
Running latest version: 1.7.73
sanitized URL is https://www.instagram.com/handmadefont/
Found album ripper: com.rarchives.ripme.ripper.rippers.InstagramRipper
sanitized URL is https://www.instagram.com/handmadefont/
Found album ripper: com.rarchives.ripme.ripper.rippers.InstagramRipper
Using album title 'instagram_handmadefont'
[+] Creating directory: C:\Users\tim\Desktop\rips\instagram_handmadefont
Set working directory to: C:\Users\tim\Desktop\rips\instagram_handmadefont
Initializing Main thread pool with 5 threads
Retrieving https://www.instagram.com/handmadefont/
{csrftoken=1O4gQuPeP0WbPhxMwN0u0O3w2nYBigPg, mcd=3, mid=XBRfJQALAAG9UnUQsyhj0jxg8eZ-, urlgen="{\"24.155.244.133\": 7459}:1gXzBG:-ylGWsv1m5JDjLPF0WNuiDEShsw", rur=ATN}
Could not find query_hash on https://www.instagram.com/static/bundles/metro/ProfilePageContainer.js/19b6df5c0bbd.js
url: https://scontent-dfw5-1.cdninstagram.com/vp/a0218a0caf384c7dfa6fde8eebb954ba/5C8E1DFC/t51.2885-15/e35/46788081_196324397986315_8107439550810292224_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com, prefix: 2018_12_14_01:00_, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/a0218a0caf384c7dfa6fde8eebb954ba/5C8E1DFC/t51.2885-15/e35/46788081_196324397986315_8107439550810292224_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_14_01_00_46788081_196324397986315_8107439550810292224_n.jpg
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/a0218a0caf384c7dfa6fde8eebb954ba/5C8E1DFC/t51.2885-15/e35/46788081_196324397986315_8107439550810292224_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
url: https://scontent-dfw5-1.cdninstagram.com/vp/eca384e457620f1164a05aba0b7880f9/5C9C7D4A/t51.2885-15/e35/47070992_321151575156267_5090526115462643712_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com, prefix: 2018_12_14_06:30_, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/eca384e457620f1164a05aba0b7880f9/5C9C7D4A/t51.2885-15/e35/47070992_321151575156267_5090526115462643712_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_14_06_30_47070992_321151575156267_5090526115462643712_n.jpg
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/eca384e457620f1164a05aba0b7880f9/5C9C7D4A/t51.2885-15/e35/47070992_321151575156267_5090526115462643712_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
Status code: 200
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/a0218a0caf384c7dfa6fde8eebb954ba/5C8E1DFC/t51.2885-15/e35/46788081_196324397986315_8107439550810292224_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_14_01_00_46788081_196324397986315_8107439550810292224_n.jpg
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/eca384e457620f1164a05aba0b7880f9/5C9C7D4A/t51.2885-15/e35/47070992_321151575156267_5090526115462643712_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_14_06_30_47070992_321151575156267_5090526115462643712_n.jpg
url: https://scontent-dfw5-1.cdninstagram.com/vp/fbeb4fc567aa06cf46a6585b9cc3b66e/5C177902/t50.2886-16/47365761_736616846694242_1637700325936726016_n.mp4, prefix: 2018_12_13_08:31_, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/fbeb4fc567aa06cf46a6585b9cc3b66e/5C177902/t50.2886-16/47365761_736616846694242_1637700325936726016_n.mp4 to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_13_08_31_47365761_736616846694242_1637700325936726016_n.mp4
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/fbeb4fc567aa06cf46a6585b9cc3b66e/5C177902/t50.2886-16/47365761_736616846694242_1637700325936726016_n.mp4 Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/fbeb4fc567aa06cf46a6585b9cc3b66e/5C177902/t50.2886-16/47365761_736616846694242_1637700325936726016_n.mp4 as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_13_08_31_47365761_736616846694242_1637700325936726016_n.mp4
url: https://scontent-dfw5-1.cdninstagram.com/vp/364ac03cb09baff7d027daf034b183f8/5C167D7E/t50.2886-16/48558100_1176500279180538_5365901650202460160_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com, prefix: 2018_12_13_12:31_, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/364ac03cb09baff7d027daf034b183f8/5C167D7E/t50.2886-16/48558100_1176500279180538_5365901650202460160_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_13_12_31_48558100_1176500279180538_5365901650202460160_n.mp4
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/364ac03cb09baff7d027daf034b183f8/5C167D7E/t50.2886-16/48558100_1176500279180538_5365901650202460160_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/364ac03cb09baff7d027daf034b183f8/5C167D7E/t50.2886-16/48558100_1176500279180538_5365901650202460160_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_13_12_31_48558100_1176500279180538_5365901650202460160_n.mp4
url: https://scontent-dfw5-1.cdninstagram.com/vp/c2de1f77515b46a093599799c001a256/5C16B411/t50.2886-16/48088607_353071638815149_4955413419357372416_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com, prefix: 2018_12_13_07:01_, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/c2de1f77515b46a093599799c001a256/5C16B411/t50.2886-16/48088607_353071638815149_4955413419357372416_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_13_07_01_48088607_353071638815149_4955413419357372416_n.mp4
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/c2de1f77515b46a093599799c001a256/5C16B411/t50.2886-16/48088607_353071638815149_4955413419357372416_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
url: https://scontent-dfw5-1.cdninstagram.com/vp/f9439273c022167903223bb770e85471/5C9641EF/t51.2885-15/e35/46431500_528242501012273_6340447536599269376_n.jpg, prefix: 2018_12_13_01:00_, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/f9439273c022167903223bb770e85471/5C9641EF/t51.2885-15/e35/46431500_528242501012273_6340447536599269376_n.jpg to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_13_01_00_46431500_528242501012273_6340447536599269376_n.jpg
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/f9439273c022167903223bb770e85471/5C9641EF/t51.2885-15/e35/46431500_528242501012273_6340447536599269376_n.jpg Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
url: https://scontent-dfw5-1.cdninstagram.com/vp/c69939d0b6acc19ce8e26b3d803191e0/5CAE62A1/t51.2885-15/e35/43163597_209591556616100_8070099538930565120_n.jpg, prefix: 2018_12_12_09:00_, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/c69939d0b6acc19ce8e26b3d803191e0/5CAE62A1/t51.2885-15/e35/43163597_209591556616100_8070099538930565120_n.jpg to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_09_00_43163597_209591556616100_8070099538930565120_n.jpg
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/c69939d0b6acc19ce8e26b3d803191e0/5CAE62A1/t51.2885-15/e35/43163597_209591556616100_8070099538930565120_n.jpg Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/f9439273c022167903223bb770e85471/5C9641EF/t51.2885-15/e35/46431500_528242501012273_6340447536599269376_n.jpg as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_13_01_00_46431500_528242501012273_6340447536599269376_n.jpg
Status code: 200
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/c2de1f77515b46a093599799c001a256/5C16B411/t50.2886-16/48088607_353071638815149_4955413419357372416_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_13_07_01_48088607_353071638815149_4955413419357372416_n.mp4
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/c69939d0b6acc19ce8e26b3d803191e0/5CAE62A1/t51.2885-15/e35/43163597_209591556616100_8070099538930565120_n.jpg as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_09_00_43163597_209591556616100_8070099538930565120_n.jpg
url: https://scontent-dfw5-1.cdninstagram.com/vp/1a42ea88d6c2ff187cfd99ca5978768d/5C923967/t51.2885-15/e35/46197487_334502704038096_2919694668759302144_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com, prefix: 2018_12_12_04:30_BrS0c2ZF1Mn, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/1a42ea88d6c2ff187cfd99ca5978768d/5C923967/t51.2885-15/e35/46197487_334502704038096_2919694668759302144_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_04_30_BrS0c2ZF1Mn46197487_334502704038096_2919694668759302144_n.jpg
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/1a42ea88d6c2ff187cfd99ca5978768d/5C923967/t51.2885-15/e35/46197487_334502704038096_2919694668759302144_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
url: https://scontent-dfw5-1.cdninstagram.com/vp/bdda04176df901388b33e84f1bf2fa22/5C966F7D/t51.2885-15/e35/46566144_306039356911881_542151668779712512_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com,
prefix: 2018_12_12_04:30_BrS0c2ZF1Mn, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/bdda04176df901388b33e84f1bf2fa22/5C966F7D/t51.2885-15/e35/46566144_306039356911881_542151668779712512_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_04_30_BrS0c2ZF1Mn46566144_306039356911881_542151668779712512_n.jpg
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/bdda04176df901388b33e84f1bf2fa22/5C966F7D/t51.2885-15/e35/46566144_306039356911881_542151668779712512_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/1a42ea88d6c2ff187cfd99ca5978768d/5C923967/t51.2885-15/e35/46197487_334502704038096_2919694668759302144_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_04_30_BrS0c2ZF1Mn46197487_334502704038096_2919694668759302144_n.jpg
Status code: 200
url: https://scontent-dfw5-1.cdninstagram.com/vp/4220fb3a331ea1779daa896dd00f6e50/5C8D7B85/t51.2885-15/e35/46708229_297231327585903_732646275949789184_n.jpg, prefix: 2018_12_12_04:30_BrS0c2ZF1Mn, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/4220fb3a331ea1779daa896dd00f6e50/5C8D7B85/t51.2885-15/e35/46708229_297231327585903_732646275949789184_n.jpg to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_04_30_BrS0c2ZF1Mn46708229_297231327585903_732646275949789184_n.jpg
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/bdda04176df901388b33e84f1bf2fa22/5C966F7D/t51.2885-15/e35/46566144_306039356911881_542151668779712512_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_04_30_BrS0c2ZF1Mn46566144_306039356911881_542151668779712512_n.jpg
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/4220fb3a331ea1779daa896dd00f6e50/5C8D7B85/t51.2885-15/e35/46708229_297231327585903_732646275949789184_n.jpg Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/4220fb3a331ea1779daa896dd00f6e50/5C8D7B85/t51.2885-15/e35/46708229_297231327585903_732646275949789184_n.jpg as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_04_30_BrS0c2ZF1Mn46708229_297231327585903_732646275949789184_n.jpg
url: https://scontent-dfw5-1.cdninstagram.com/vp/2dc4b6492f767afcc776508efaee75d4/5C8C3C67/t51.2885-15/e35/46797745_370407986861761_5769865774185316352_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com, prefix: 2018_12_12_12:30_, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/2dc4b6492f767afcc776508efaee75d4/5C8C3C67/t51.2885-15/e35/46797745_370407986861761_5769865774185316352_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_12_30_46797745_370407986861761_5769865774185316352_n.jpg
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/2dc4b6492f767afcc776508efaee75d4/5C8C3C67/t51.2885-15/e35/46797745_370407986861761_5769865774185316352_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/2dc4b6492f767afcc776508efaee75d4/5C8C3C67/t51.2885-15/e35/46797745_370407986861761_5769865774185316352_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_12_30_46797745_370407986861761_5769865774185316352_n.jpg
url: https://scontent-dfw5-1.cdninstagram.com/vp/780166c632713d39e0852dd585ba0fa4/5C16B2A7/t50.2886-16/48432510_322012271740595_3855139164303392768_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com, prefix: 2018_12_12_07:31_, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/780166c632713d39e0852dd585ba0fa4/5C16B2A7/t50.2886-16/48432510_322012271740595_3855139164303392768_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_07_31_48432510_322012271740595_3855139164303392768_n.mp4
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/780166c632713d39e0852dd585ba0fa4/5C16B2A7/t50.2886-16/48432510_322012271740595_3855139164303392768_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/780166c632713d39e0852dd585ba0fa4/5C16B2A7/t50.2886-16/48432510_322012271740595_3855139164303392768_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_07_31_48432510_322012271740595_3855139164303392768_n.mp4
url: https://scontent-dfw5-1.cdninstagram.com/vp/e8addd3318b7bdac19a63bef0e3372e3/5C177BD5/t50.2886-16/48563026_529908997494746_2722530776242454528_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com, prefix: 2018_12_12_01:01_, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/e8addd3318b7bdac19a63bef0e3372e3/5C177BD5/t50.2886-16/48563026_529908997494746_2722530776242454528_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_01_01_48563026_529908997494746_2722530776242454528_n.mp4
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/e8addd3318b7bdac19a63bef0e3372e3/5C177BD5/t50.2886-16/48563026_529908997494746_2722530776242454528_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/e8addd3318b7bdac19a63bef0e3372e3/5C177BD5/t50.2886-16/48563026_529908997494746_2722530776242454528_n.mp4?_nc_ht=scontent-dfw5-1.cdninstagram.com as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_12_01_01_48563026_529908997494746_2722530776242454528_n.mp4
url: https://scontent-dfw5-1.cdninstagram.com/vp/d139910e7e67503d17816e99142cc5c1/5CAA8B49/t51.2885-15/e35/46568396_211742366394928_6468603236088545280_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com, prefix: 2018_12_11_09:40_BrQzFrtld0e, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/d139910e7e67503d17816e99142cc5c1/5CAA8B49/t51.2885-15/e35/46568396_211742366394928_6468603236088545280_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_11_09_40_BrQzFrtld0e46568396_211742366394928_6468603236088545280_n.jpg
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/d139910e7e67503d17816e99142cc5c1/5CAA8B49/t51.2885-15/e35/46568396_211742366394928_6468603236088545280_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
url: https://scontent-dfw5-1.cdninstagram.com/vp/8a3cad0ff0b9a55b8a666ac80e0b4e44/5C9483D0/t51.2885-15/e35/46085441_446685912531272_632875929420431360_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com,
prefix: 2018_12_11_09:40_BrQzFrtld0e, subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/vp/8a3cad0ff0b9a55b8a666ac80e0b4e44/5C9483D0/t51.2885-15/e35/46085441_446685912531272_632875929420431360_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_11_09_40_BrQzFrtld0e46085441_446685912531272_632875929420431360_n.jpg
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/vp/8a3cad0ff0b9a55b8a666ac80e0b4e44/5C9483D0/t51.2885-15/e35/46085441_446685912531272_632875929420431360_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
Found image url #1: https://scontent-dfw5-1.cdninstagram.com/5C8E1DFC/t51.2885-15/e35/46788081_196324397986315_8107439550810292224_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com
url: https://scontent-dfw5-1.cdninstagram.com/5C8E1DFC/t51.2885-15/e35/46788081_196324397986315_8107439550810292224_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com, prefix: , subdirectory, referrer: null, cookies: null, fileName: null
Downloading https://scontent-dfw5-1.cdninstagram.com/5C8E1DFC/t51.2885-15/e35/46788081_196324397986315_8107439550810292224_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com to C:\Users\tim\Desktop\rips\instagram_handmadefont\46788081_196324397986315_8107439550810292224_n.jpg
Sleeping 2500ms
    Downloading file: https://scontent-dfw5-1.cdninstagram.com/5C8E1DFC/t51.2885-15/e35/46788081_196324397986315_8107439550810292224_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/d139910e7e67503d17816e99142cc5c1/5CAA8B49/t51.2885-15/e35/46568396_211742366394928_6468603236088545280_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_11_09_40_BrQzFrtld0e46568396_211742366394928_6468603236088545280_n.jpg
Status code: 200
Status code: 403
[!] Non-retriable status code 403 while downloading from https://scontent-dfw5-1.cdninstagram.com/5C8E1DFC/t51.2885-15/e35/46788081_196324397986315_8107439550810292224_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com
[+] Saved https://scontent-dfw5-1.cdninstagram.com/vp/8a3cad0ff0b9a55b8a666ac80e0b4e44/5C9483D0/t51.2885-15/e35/46085441_446685912531272_632875929420431360_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com as C:\Users\tim\Desktop\rips\instagram_handmadefont\2018_12_11_09_40_BrQzFrtld0e46085441_446685912531272_632875929420431360_n.jpg
String to md5 is "cec7a282b9ba3c7d4c1ec4f945f5c64e:{"id":"1300751410","first":12,"after":"QVFCT3VIa2VaTy0zcmhsYnREcDBoblVTWXBrSzRXMUJkUXotWWtyN0dHMTdfN3RLNWJuNFBUdFA4dGc0MUxZUnNHRmN5Si1fc25paUVtY0Fwd1UwTGVCag=="}"
32d8f56da629176ef22220247472b7c2
https://www.instagram.com/graphql/query/?query_hash=null&variables={"id":"1300751410","first":12,"after":"QVFCT3VIa2VaTy0zcmhsYnREcDBoblVTWXBrSzRXMUJkUXotWWtyN0dHMTdfN3RLNWJuNFBUdFA4dGc0MUxZUnNHRmN5Si1fc25paUVtY0Fwd1UwTGVCag=="}
Unable to get query_hash
Server returned HTTP response code: 400 for URL: https://www.instagram.com/graphql/query/?query_hash=null&variables={"id":"1300751410","first":12,"after":"QVFCT3VIa2VaTy0zcmhsYnREcDBoblVTWXBrSzRXMUJkUXotWWtyN0dHMTdfN3RLNWJuNFBUdFA4dGc0MUxZUnNHRmN5Si1fc25paUVtY0Fwd1UwTGVCag=="}

Got exception while running ripper:
java.lang.NullPointerException
        at com.rarchives.ripme.ripper.rippers.InstagramRipper.pageHasImages(InstagramRipper.java:402)
        at com.rarchives.ripme.ripper.rippers.InstagramRipper.getNextPage(InstagramRipper.java:383)
        at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:92)
        at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:561)
        at java.base/java.lang.Thread.run(Thread.java:834)
Waiting for threads to finish
   Rip completed!
Saved configuration to C:\Users\tim\AppData\Local\ripme\rip.properties
```

**Comment by Ectomind1990** [comment]
Think the instagram desktop site changed in the last 2 days. Maybe would need a new release of ripme to keep up with the changes
