### ISSUE TITLE
Instagram shows error:null

### ISSUE THREAD

**Issue by BurhanDanger** [RipMeApp/ripme#1109]
* Ripme version: `1.7.73`
* Java version: 
```
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-b26)
OpenJDK 64-Bit Server VM (build 25.192-b26, mixed mode)
```

* Operating system:  `Archlinux` 

* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/madelame/
* Please include any additional information about how to reproduce the problem:

## Actual Behavior
log.txt
```
2018-12-15 22:02:20,307 ERROR ripper.AbstractRipper .getQHash() Could not find query_hash on https://www.instagram.com/static/bundles/metro/ProfilePageContainer.js/19b6df5c0bbd.js
2018-12-15 22:02:22,359 ERROR ripper.DownloadFileThread .run() [!] Non-retriable status code 403 while downloading from https://instagram.fdac6-1.fna.fbcdn.net/5CAB5087/t51.2885-15/e35/46841045_460584781137047_5236403275627616008_n.jpg?_nc_ht=instagram.fdac6-1.fna.fbcdn.net
2018-12-15 22:02:24,713 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.pageHasImages(InstagramRipper.java:402)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getNextPage(InstagramRipper.java:383)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:92)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:561)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by BurhanDanger** [comment]
duplicate #731

**Comment by BurhanDanger** [comment]
It was my bad, I didn't check carefully before making this issue. After I saw open duplicate issue I let it remain open, since it's not fixed.

**Comment by cyian-1756** [comment]
> After I saw open duplicate issue I let it remain open, since it's not fixed.

It should be fixed as of 1.7.74
