### ISSUE TITLE
Reddit: RipMe often hangs while ripping

### ISSUE THREAD

**Issue by Whocaresman** [RipMeApp/ripme#1160]
* Ripme version: 1.7.76
* Java version:  Version 8 Build 191
* Operating system:  Windows 10

RipMe seems to hang often when ripping reddit. It appears to happen more often if a redditor has submitted a lot of content, though I can't be sure what the exact issue is.

**Comment by goodboi69** [comment]
This is a known issue. There's a thread here somewhere.

**Comment by oldesoul95** [comment]
Here's the earlier post. Still experiencing it too.

https://github.com/RipMeApp/ripme/issues/1017

**Comment by KurtCocain** [comment]
Yes! I am experiencing exactly this. Even with the last 78 or 79, whatever it is.

**Comment by KurtCocain** [comment]
Heres some of the log

`2019-03-02 01:28:21,861 DEBUG utils.RipUtils .getFilesFromURL() Checking https://gfycat.com/DelayedHarmlessGrayreefshark
2019-03-02 01:28:21,861 DEBUG utils.RipUtils .getFilesFromURL() Fetching gfycat page https://gfycat.com/DelayedHarmlessGrayreefshark
2019-03-02 01:28:21,861 INFO  ripper.AbstractRipper .getVideoURL() Retrieving https://gfycat.com/DelayedHarmlessGrayreefshark
2019-03-02 01:28:21,961 WARN  utils.Http .response() Error while loading https://gfycat.com/DelayedHarmlessGrayreefshark
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://gfycat.com/DelayedHarmlessGrayreefshark
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.utils.Http.get(Http.java:110)
	at com.rarchives.ripme.ripper.rippers.GfycatRipper.getVideoURL(GfycatRipper.java:103)
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:70)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:260)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:193)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:562)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-02 01:28:21,962 WARN  utils.RipUtils .getFilesFromURL() Exception while retrieving gfycat page:
java.io.IOException: Failed to load https://gfycat.com/DelayedHarmlessGrayreefshark after 1 attempts
	at com.rarchives.ripme.utils.Http.response(Http.java:137)
	at com.rarchives.ripme.utils.Http.get(Http.java:110)
	at com.rarchives.ripme.ripper.rippers.GfycatRipper.getVideoURL(GfycatRipper.java:103)
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:70)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:260)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:193)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:562)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://gfycat.com/DelayedHarmlessGrayreefshark
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	... 9 more
2019-03-02 01:28:23,962 DEBUG ripper.AbstractRipper .waitForThreads() Waiting for threads to finish
`
