### ISSUE TITLE
1.7.76 fail to rip DeviantArt gallery and e621.net

### ISSUE THREAD

**Issue by Gromily4** [RipMeApp/ripme#1171]
* Ripme version: 1.7.76
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred: 
https://e621.net/post/index/1/feretta  
for https://derpibooru.org/
* Please include any additional information about how to reproduce the problem: none

## Expected Behavior
Rip normally.

## Actual Behavior

for https://derpibooru.org/tags/artist-colon-sugarlesspaints full download you need to use the filter"Maximum Spoilers" 

the download fails e621.
2019-01-16 22:03:41,172 ERROR rippers.E621Ripper .getFullSizedImage() Unable to get full sized image from /post/show/1178563
2019-01-16 22:03:41,242 WARN  utils.Http .response() Error while loading https://e621.net/post/show/1173392
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:449)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.utils.Http.get(Http.java:110)
	at com.rarchives.ripme.ripper.rippers.E621Ripper.getFullSizedImage(E621Ripper.java:59)
	at com.rarchives.ripme.ripper.rippers.E621Ripper.getURLsFromPage(E621Ripper.java:85)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:103)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:562)
	at java.lang.Thread.run(Unknown Source)
2019-01-16 22:03:41,252 ERROR rippers.E621Ripper .getFullSizedImage() Unable to get full sized image from /post/show/1173392
2019-01-16 22:03:41,312 WARN  utils.Http .response() Error while loading https://e621.net/post/show/1165356
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:449)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.utils.Http.get(Http.java:110)
	at com.rarchives.ripme.ripper.rippers.E621Ripper.getFullSizedImage(E621Ripper.java:59)
	at com.rarchives.ripme.ripper.rippers.E621Ripper.getURLsFromPage(E621Ripper.java:85)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:103)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:562)
	at java.lang.Thread.run(Unknown Source)
2019-01-16 22:03:41,312 ERROR rippers.E621Ripper .getFullSizedImage() Unable to get full sized image from /post/show/1165356
2019-01-16 22:03:41,472 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.net.MalformedURLException
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:121)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:562)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	... 6 more

**Comment by rautamiekka** [comment]
Hmm, 1.7.76 works perfectly on the Derpibooru one, but I get the same problem with e621 all the way to 1.7.30 which is the oldest I tested.

**Comment by Gromily4** [comment]
Yes s https://derpibooru.org/ works, but if you do not apply the filter settings on a particular page, downloads only 152 files, and their filter "Maximum Spoilers" https://derpibooru.org/tags/artist-colon-sugarlesspaints will 1062 files.

**Comment by rautamiekka** [comment]
^ The spoilers one would be useful if you wanna avoid spoilers, otherwise 'Everything' filter is what you need for unrestricted ripping.

**Comment by Gromily4** [comment]
well, since install this 'Everything' filter in the program, since I did not find anything like this

**Comment by metaprime** [comment]
Title previously said DeviantArt but it seems to actually be derpibooru.

I've also just pushed another fix for partially broken E621
