### ISSUE TITLE
[Listal] Unable to download images. ( PKIX path building failed...)

### ISSUE THREAD

**Issue by Tush-r** [RipMeApp/ripme#1184]
* Ripme version: Not required.
* Java version: JDK 1.8 and JDK 11
* Operating system: Windows 7

## Issue
I'm writing a ripper for listal.com which is failing to download images with a SSLHandshakeException.

Url: [Sample Link.](https://iv1.lisimg.com/image/16278749/600full-swords-of-sorrow-artwork.jpg)

Error Log: 

> [!] Exception while downloading file: https://iv1.lisimg.com/image/16278749/600full-swords-of-sorrow-artwork.jpg - PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[!] Exceeded maximum retries (1) for URL https://iv1.lisimg.com/image/16278749/600full-swords-of-sorrow-artwork.jpg
IOException
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1329)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1204)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1151)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
	at com.rarchives.ripme.ripper.DownloadFileThread.run(DownloadFileThread.java:138)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:321)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:221)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1313)
	... 17 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
	... 23 more

## Actual Behavior
To download images successfully.

If anyone can run the below code and let me know the results.

> import java.io.IOException;
import java.net.URL;
import javax.net.ssl.HttpsURLConnection;
public class Test {
    public static void main(String[] args) {
        try {
            URL url = new URL("https://iv1.lisimg.com/image/16278749/600full-swords-of-sorrow-artwork.jpg");
            HttpsURLConnection con = (HttpsURLConnection) url.openConnection();
            con.connect();
            System.out.println(con.getResponseCode());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

**Comment by cyian-1756** [comment]
From [this](https://community.oracle.com/thread/1535072) oracle community post it looks like by default java does not trust certs from GlobalSign

Looks like we'll have to add globalSign to ripme as a trusted issuer. I also think we should print a message when a user rips from a site using GlobalSign that GlobalSign trust was added by us it's not trusted by java

**Comment by Tush-r** [comment]
> 
> 
> From [this](https://community.oracle.com/thread/1535072) oracle community post it looks like by default java does not trust certs from GlobalSign
> 
> Looks like we'll have to add globalSign to ripme as a trusted issuer. I also think we should print a message when a user rips from a site using GlobalSign that GlobalSign trust was added by us it's not trusted by java

GlobalSign is trusted. listal.com uses GlobalSign and works smoothly.
I think it has to do with TLS 1.3
