### ISSUE TITLE
Doesn't download gfycat from reddit

### ISSUE THREAD

**Issue by tayser1** [RipMeApp/ripme#1188]
* Ripme version: 1.7.77

## Expected Behavior
Ripme should have downloaded all files from reddit user imgur, v.reddit, gyfcat etc.

## Actual Behavior
Ripme only downloads from imgur and v.reddit. None from gyfcat.

2019-01-23 13:30:46,952 INFO  ripper.AbstractRipper .getVideoURL() Retrieving https://gfycat.com/EnviousCommonGraysquirrel
2019-01-23 13:30:47,281 WARN  utils.RipUtils .getFilesFromURL() Exception while retrieving gfycat page:
java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:72)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:233)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:166)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:562)
	at java.lang.Thread.run(Unknown Source)

**Comment by KurtCocain** [comment]
Easiest problem to confirm tbh, on all my 4 stations I tested it to check if i f'd something, they all dont work.
win7 win8 win 10 win10
all 64 bit same jav version

**Comment by Auwen** [comment]
Same here

**Comment by timbro1** [comment]
same issue here
