### ISSUE TITLE
Reddit: RipMe hangs while ripping from GUI, errors thrown when ripping from CLI

### ISSUE THREAD

**Issue by flerpmcnasty** [RipMeApp/ripme#1243]
* Ripme version: 1.7.80

* Java version: 

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

* Operating system: 

Microsoft Windows [Version 10.0.17134.648]

* Exact URL you were trying to rip when the problem occurred:

https://old.reddit.com/user/jenn_lyn21

* Please include any additional information about how to reproduce the problem:

Rip from GUI it eventually hangs up indefinitely. Have to close/kill the app. 
Rip from CLI it throws errors but eventually the app stops running. 

2 errors:
  java.io.IOException: Invalid argument
  Exception in thread "pool-1-thread-8" java.lang.NullPointerException

See full CLI output below in Actual Behavior section.

## Expected Behavior

Rip the reddit user's content from either CLI or GUI without hanging up or throwing errors.

## Actual Behavior

Rip from GUI hangs.
Rip from CLI throws errors but completes.

F:\>java -jar ripme.jar --u "https://old.reddit.com/user/jenn_lyn21"
Loaded C:\Users\Foo\AppData\Local\ripme\rip.properties
[!] Unable to rip URL: https://www.reddit.com/r/jenn_lyn21/?st=JP63GSHP&amp;sh=a0612812
Exception:
java.io.IOException: Invalid argument
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(Unknown Source)
        at java.io.File.getCanonicalPath(Unknown Source)
        at com.rarchives.ripme.utils.Utils.removeCWD(Utils.java:291)
        at com.rarchives.ripme.ripper.DownloadFileThread.<init>(DownloadFileThread.java:51)
        at com.rarchives.ripme.ripper.AlbumRipper.addURLToDownload(AlbumRipper.java:81)
        at com.rarchives.ripme.ripper.AlbumRipper.addURLToDownload(AlbumRipper.java:96)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:277)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:193)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
        at com.rarchives.ripme.App.rip(App.java:99)
        at com.rarchives.ripme.App.ripURL(App.java:265)
        at com.rarchives.ripme.App.handleArguments(App.java:248)
        at com.rarchives.ripme.App.main(App.java:74)
Exception:
java.io.IOException: Invalid argument
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(Unknown Source)
        at java.io.File.getCanonicalPath(Unknown Source)
        at com.rarchives.ripme.utils.Utils.removeCWD(Utils.java:291)
        at com.rarchives.ripme.ripper.DownloadFileThread.<init>(DownloadFileThread.java:51)
        at com.rarchives.ripme.ripper.AlbumRipper.addURLToDownload(AlbumRipper.java:81)
        at com.rarchives.ripme.ripper.AlbumRipper.addURLToDownload(AlbumRipper.java:96)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:277)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:193)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
        at com.rarchives.ripme.App.rip(App.java:99)
        at com.rarchives.ripme.App.ripURL(App.java:265)
        at com.rarchives.ripme.App.handleArguments(App.java:248)
        at com.rarchives.ripme.App.main(App.java:74)
Exception in thread "pool-1-thread-8" java.lang.NullPointerException
        at com.rarchives.ripme.ripper.DownloadFileThread.run(DownloadFileThread.java:247)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by Gamerick** [comment]
So from a glance at the error it looks like the url is getting somewhat garbled somewhere. I'm currently about to head to bed but I'll take a proper look at it tomorrow morning.

**Comment by cyian-1756** [comment]
> https://www.reddit.com/r/jenn_lyn21/?st=JP63GSHP&amp;sh=a0612812

I imagine this is happening because of the ;

Try ripping https://www.reddit.com/r/jenn_lyn21

**Comment by flerpmcnasty** [comment]
The URL I attempted to rip was already:  https://old.reddit.com/user/jenn_lyn21

https://www.reddit.com/r/jenn_lyn21 produces the same exact errors / behavior from GUI & CLI..

The problematic URL you mention can be found in the JSON output here: https://www.reddit.com/r/jenn_lyn21.json
