### ISSUE TITLE
can't load the page author hentai-foundry.com

### ISSUE THREAD

**Issue by Gromily4** [RipMeApp/ripme#1277]
Ripme version:1.7.82
    Java version: 1.8.0_201
    Operating system: Windows 7 Version 6.1.7601
    Exact URL you were trying to rip when the problem occurred:http://www.hentai-foundry.com/pictures/user/turk128
    Please include any additional information about how to reproduce the problem:
    http://www.hentai-foundry.com/pictures/user/turk128
    As above, an error also occurs when specify a single page.

Log:
[log.txt](https://github.com/RipMeApp/ripme/files/3075709/log.txt)

2019-04-13 08:48:28,690 WARN  utils.Http .response() Error while loading https://www.hentai-foundry.com/pictures/user/turk128/334485/Rough-Date
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:453)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.utils.Http.get(Http.java:110)
	at com.rarchives.ripme.ripper.rippers.HentaifoundryRipper.getURLsFromPage(HentaifoundryRipper.java:158)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:104)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:578)
	at java.lang.Thread.run(Unknown Source)
2019-04-13 08:48:28,690 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.HentaifoundryRipper.getURLsFromPage(HentaifoundryRipper.java:167)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:104)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:578)
	at java.lang.Thread.run(Unknown Source)

downloads only 150 pages and is interrupted.

**Comment by cyian-1756** [comment]
> java.net.SocketTimeoutException: Read timed out

Looks like this was caused by a network issue. Try waiting a bit and ripping it again to see if that works

**Comment by Gromily4** [comment]
not similar. always interrupted in one place. tried to download a different author, there is success, and this problem remains. and swings not in order and parts, on one page part, on another part.
