### ISSUE TITLE
Artstation no longer working

### ISSUE THREAD

**Issue by Butterfly-Dragon** [RipMeApp/ripme#1287]
* Ripme version: 1.7.82
* Java version: java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
* Operating system:  Microsoft Windows [Version 10.0.17763.437]
* Exact URL you were trying to rip when the problem occurred:
https://www.artstation.com/2buiart
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

the ripper would get me the pictures from the gallery

## Actual Behavior

Error while loading https://www.artstation.com/users/2buiart/quick.json
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://www.artstation.com/users/2buiart/quick.json
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.getJSON(Http.java:120)
        at com.rarchives.ripme.ripper.rippers.ArtStationRipper.getGID(ArtStationRipper.java:64)
        at com.rarchives.ripme.ripper.AbstractRipper.getAlbumTitle(AbstractRipper.java:498)
        at com.rarchives.ripme.ripper.AlbumRipper.setWorkingDir(AlbumRipper.java:193)
        at com.rarchives.ripme.ripper.AbstractRipper.setup(AbstractRipper.java:179)
        at com.rarchives.ripme.App.rip(App.java:98)
        at com.rarchives.ripme.App.handleArguments(App.java:182)
        at com.rarchives.ripme.App.main(App.java:74)

**Comment by Brianwindows102018** [comment]
any fix for this?

**Comment by cyian-1756** [comment]
The fix has been merged and should be in the next release of ripme

**Comment by UnforeseenOcean** [comment]
1.7.83 still has this issue!
![Image 142](https://user-images.githubusercontent.com/11834016/57371652-48cb5e80-71ce-11e9-99f9-a64ffbf1f77f.png)

**Comment by UnforeseenOcean** [comment]
Oh no, I worded it incorrectly. What I meant was 1.7.83 **also** has the issue, not **still** has issue.

**Comment by Butterfly-Dragon** [comment]
> Oh no, I worded it incorrectly. What I meant was 1.7.83 **also** has the issue, not **still** has issue.

@UnforeseenOcean last reply was 4 days ago when he said he solved the problem. 1.7.83 was much before that. Calm down it will be solved next release.
