### ISSUE TITLE
can't rip instagram

### ISSUE THREAD

**Issue by gh0sti** [RipMeApp/ripme#1314]
* Ripme version:most recent1.7.83
* Java version:  8.192
* Operating system: win 10

* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/theellenshow/

## Expected Behavior

Detail the expected behavior here.
should rip without issue

## Actual Behavior

JSONObject["rhx_gis"] not found.

any instagram link does this.

**Comment by AlexFiala** [comment]
Seeing the same issue in v1.7.83

**Comment by ji1t** [comment]
same issue v 7.83 tried only with instagram

**Comment by skylar01** [comment]
same issue v1.7.83

**Comment by ds89snsadbf** [comment]
```Loaded /Users/xxxxx/Library/Application Support/ripme/rip.properties
Loaded log4j.properties
Initialized ripme v1.7.83
Setting locale to en_US
Loading history from /Users/xxxxx/Library/Application Support/ripme/history.json
Retrieving https://raw.githubusercontent.com/ripmeapp/ripme/master/ripme.json
This version (1.7.83) is the same or newer than the website's version (1.7.83)
Running latest version: 1.7.83
sanitized URL is https://www.instagram.com/xxxxxxxxxx/
Found album ripper: com.rarchives.ripme.ripper.rippers.InstagramRipper
sanitized URL is https://www.instagram.com/xxxxxxxxxx/
Found album ripper: com.rarchives.ripme.ripper.rippers.InstagramRipper
Using album title 'instagram_xxxxxxxxxx'
[+] Creating directory: ./rips/instagram_xxxxxxxxxx
Set working directory to: /Users/xxxxx/Desktop/rips/instagram_xxxxxxxxxx
Initializing Main thread pool with 5 threads
Retrieving https://www.instagram.com/xxxxxxxxxx/
{urlgen="{\"54.213.100.75\": 16509}:1hRix1:-saPjOmXouu-43Ru_EpCakoNRSM", mid=XN8RswALAAHX8O47213c26-BpBm8, rur=PRN, csrftoken=nhZjbvXNStXUZ38xzrGbOYUwZoP7O7zG}
https://www.instagram.com/static/bundles/metro/ProfilePageContainer.js/5a832fed3cc1.js
Got exception while running ripper:
org.json.JSONException: JSONObject["rhx_gis"] not found.
	at org.json.JSONObject.get(JSONObject.java:473)
	at org.json.JSONObject.getString(JSONObject.java:654)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getURLsFromJSON(InstagramRipper.java:246)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:58)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.base/java.lang.Thread.run(Thread.java:834)
Waiting for threads to finish
   Rip completed!
Deleting empty directory /Users/xxxxx/Desktop/rips/instagram_xxxxxxxxxx
^CSaved window position (x=291, y=154, w=854, h=518)
```

**Comment by samsepiol59** [comment]
same issue, latest version

**Comment by UnforeseenOcean** [comment]
Confirmed
![Image 283](https://user-images.githubusercontent.com/11834016/57965939-5333e800-7986-11e9-9532-5f4d507d1aeb.png)

**Comment by AranciataExcess** [comment]
+1

Getting same issue.
