### ISSUE TITLE
Ripme 1.6.0+ crashes at startup

### ISSUE THREAD

**Issue by nzbtuxnews** [RipMeApp/ripme#132]
* Ripme version: 1.6.2 (problem occurs with 1.6.0+)
* Java version: java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.151-b01, mixed mode)

* Operating system: Linux Mint 17.2
## Actual Behavior

When I start the app it crashes with the following stack trace:

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/rarchives/ripme/App : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by rautamiekka** [comment]
Java 8+ required.

**Comment by cyian-1756** [comment]
This is because of your java version. Because java 1.6 and 1.7 are quite old ripme has dropped support for them. Either use 1.5.15 or update to java 8
