### ISSUE TITLE
Artstation does not download from the commandline

### ISSUE THREAD

**Issue by Butterfly-Dragon** [RipMeApp/ripme#1321]
* Ripme version: 1.7.84
* Java version:
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
* Operating system:
Microsoft Windows [Version 10.0.17763.503]

* Exact URL you were trying to rip when the problem occurred:
any artstation url. Example provided: ```https://www.artstation.com/2buiart```

* Please include any additional information about how to reproduce the problem:
## Expected Behavior

Running `start "" /min java -jar ripme.jar -R` should download all the albums in history.json

## Actual Behavior

running `start "" /min java -jar ripme.jar -R` will result in no downloads from any artstation site. The output will be instead:

`Loaded D:\Downloads\Downloader\!Ripme Artstation\rip.properties
Loaded log4j.properties
Initialized ripme v1.7.84
Loading history from D:\Downloads\Downloader\!Ripme Artstation\history.json
[!] Failed to rip URL https://www.artstation.com/2buiart
java.net.MalformedURLException: Couldn't load JSON from https://www.artstation.com/users/2buiart/quick.json
        at com.rarchives.ripme.ripper.rippers.ArtStationRipper.getGID(ArtStationRipper.java:66)
        at com.rarchives.ripme.ripper.AbstractRipper.getAlbumTitle(AbstractRipper.java:536)
        at com.rarchives.ripme.ripper.AlbumRipper.setWorkingDir(AlbumRipper.java:193)
        at com.rarchives.ripme.ripper.AbstractRipper.setup(AbstractRipper.java:179)
        at com.rarchives.ripme.App.rip(App.java:98)
        at com.rarchives.ripme.App.handleArguments(App.java:182)
        at com.rarchives.ripme.App.main(App.java:74) `

Double clicking on ripme.jar executes ripme normally. The files will then be downloaded with no problem when going in the history tab and re-downloading the checked sites.

**Comment by Butterfly-Dragon** [comment]
artstation ripper has stopped working altogether as of 2019-06-25. Gives a "couldn't load quick.json" error at the page or any gallery i try and download

**Comment by Butterfly-Dragon** [comment]
i would like to confirm that (as of today) this still does not work
