### ISSUE TITLE
DeviantArt ripper stopped working altogether

### ISSUE THREAD

**Issue by rautamiekka** [RipMeApp/ripme#1337]
* Ripme version: 1.7.84
* Java version: 
```
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```
* Operating system:  Window$ 10.0.17134.706 Enterprise x64

* Exact URL you were trying to rip when the problem occurred: https://www.deviantart.com/laszlvfx/gallery/?catpath=/ 
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
Rip normally.

## Actual Behavior
Some loser stole the ripper's account, making the ripper always fail to work:
RipMe output:
```
Downloading https://www.deviantart.com/laszlvfx/gallery/?catpath=/
Rip complete, saved to D:\_DOWNLOADS_\RipMe\rips\deviantart_laszlvfx_gallery_all
null
```

`.\rips\deviantart_laszlvfx_gallery_all\log.txt`:
```
2019-06-10 14:13:34,823 DEBUG ripper.DownloadThreadPool .initialize() Initializing Main thread pool with 1 threads
2019-06-10 14:13:34,829 INFO  ripper.AbstractRipper .rip() Retrieving https://www.deviantart.com/laszlvfx/gallery/?catpath=/
2019-06-10 14:13:35,840 INFO  ripper.AbstractRipper .updateCookie() Updating Cookies
2019-06-10 14:13:35,841 INFO  ripper.AbstractRipper .updateCookie() Old Cookies: {} 
2019-06-10 14:13:35,841 INFO  ripper.AbstractRipper .updateCookie() New Cookies: {features=deleted, agegate_state=1, auth=__c3e171e69c151f57c50f%3B%22344d90cb74975c531206b4fcbd5a0162%22, userinfo=__dbee27e2949af82a5799%3B%7B%22username%22%3A%22%22%2C%22uniqueid%22%3A%22856954f5d55d0ec494fa9425e1dab883%22%2C%22vd%22%3A%22Bc%5C%2FSLi%2CBc%5C%2FSLi%2CA%2CD%2CA%2C%2CB%2CA%2CB%2CBc%5C%2FSLi%2CBc%5C%2FSLj%2CA%2CA%2CA%2CA%2C13%2CA%2CB%2CA%2C%2CA%2CA%2CB%2CA%2CA%2C%2CA%22%7D, auth_secure=__34541ed59e034e3ea766%3B%22066d7544b52b08b8f14d0f4b1816d77f%22} 
2019-06-10 14:13:35,842 INFO  ripper.AbstractRipper .updateCookie() Merged Cookies: {features=deleted, agegate_state=1, auth=__c3e171e69c151f57c50f%3B%22344d90cb74975c531206b4fcbd5a0162%22, userinfo=__dbee27e2949af82a5799%3B%7B%22username%22%3A%22%22%2C%22uniqueid%22%3A%22856954f5d55d0ec494fa9425e1dab883%22%2C%22vd%22%3A%22Bc%5C%2FSLi%2CBc%5C%2FSLi%2CA%2CD%2CA%2C%2CB%2CA%2CB%2CBc%5C%2FSLi%2CBc%5C%2FSLj%2CA%2CA%2CA%2CA%2C13%2CA%2CB%2CA%2C%2CA%2CA%2CB%2CA%2CA%2C%2CA%22%7D, auth_secure=__34541ed59e034e3ea766%3B%22066d7544b52b08b8f14d0f4b1816d77f%22} 
2019-06-10 14:13:35,849 INFO  utils.Utils .saveConfig() Saved configuration to D:\_DOWNLOADS_\RipMe\rip.properties
2019-06-10 14:13:35,850 INFO  ripper.AbstractRipper .checkLogin() Login with Cookies: {features=deleted, agegate_state=1, auth=__c3e171e69c151f57c50f%3B%22344d90cb74975c531206b4fcbd5a0162%22, userinfo=__dbee27e2949af82a5799%3B%7B%22username%22%3A%22%22%2C%22uniqueid%22%3A%22856954f5d55d0ec494fa9425e1dab883%22%2C%22vd%22%3A%22Bc%5C%2FSLi%2CBc%5C%2FSLi%2CA%2CD%2CA%2C%2CB%2CA%2CB%2CBc%5C%2FSLi%2CBc%5C%2FSLj%2CA%2CA%2CA%2CA%2C13%2CA%2CB%2CA%2C%2CA%2CA%2CB%2CA%2CA%2C%2CA%22%7D, auth_secure=__34541ed59e034e3ea766%3B%22066d7544b52b08b8f14d0f4b1816d77f%22}
2019-06-10 14:13:37,434 INFO  ripper.AbstractRipper .checkLogin() Cookies invalid. Wrong URL: https://www.deviantart.com/users/wrong-password?url=%2fusers%2flogin&uuid=cafd0b90-8b70-11e9-a5be-f54ecafd5a59&vid=  200
2019-06-10 14:13:37,435 INFO  ripper.AbstractRipper .login() Do Login now
2019-06-10 14:13:38,968 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.DeviantartRipper.login(DeviantartRipper.java:188)
	at com.rarchives.ripme.ripper.rippers.DeviantartRipper.getFirstPage(DeviantartRipper.java:129)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:86)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.lang.Thread.run(Unknown Source)
2019-06-10 14:13:38,969 DEBUG ripper.AbstractRipper .waitForThreads() Waiting for threads to finish
2019-06-10 14:13:38,970 INFO  ripper.AbstractRipper .checkIfComplete()    Rip completed!
2019-06-10 14:13:38,970 DEBUG ripper.AbstractRipper .checkIfComplete() Changing log file back to 'ripme.log'
```

Nothing in `.\ripme.log`.

**Comment by rautamiekka** [comment]
Hmm, seems the problem was the cookie string in the config. Commenting it helped.

But even then, I tried the logins in the ripper code and they failed.

**Comment by puffinkins** [comment]
For me, it does not download most pictures unless I disable "Remember URL history" for some reason, despite never having downloaded the content.
