### ISSUE TITLE
8muses Jsoup Error-Http 403

### ISSUE THREAD

**Issue by JanLus** [RipMeApp/ripme#1338]
* Ripme version: 1.7.84
* Java version: Openjdk version "11.0.3" / Oracle java version "1.8.0_212"
* Operating system: Ubuntu (4.15.0-51-generic)
------------------------------------
Found album ripper: com.rarchives.ripme.ripper.rippers.EightmusesRipper
Found album ripper: com.rarchives.ripme.ripper.rippers.EightmusesRipper
Error while loading https://www.8muses.com/comics/album/JAB-Comics/Vanilla
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://www.8muses.com/comics/album/JAB-Comics/Vanilla
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:131)
	at com.rarchives.ripme.ripper.rippers.EightmusesRipper.getFirstPage(EightmusesRipper.java:82)
	at com.rarchives.ripme.ripper.rippers.EightmusesRipper.getAlbumTitle(EightmusesRipper.java:67)
	at com.rarchives.ripme.ripper.AlbumRipper.setWorkingDir(AlbumRipper.java:193)
	at com.rarchives.ripme.ripper.AbstractRipper.setup(AbstractRipper.java:180)
	at com.rarchives.ripme.ui.MainWindow.ripAlbum(MainWindow.java:1205)
	at com.rarchives.ripme.ui.MainWindow.ripNextAlbum(MainWindow.java:1164)
	at com.rarchives.ripme.ui.MainWindow.access$600(MainWindow.java:66)
	at com.rarchives.ripme.ui.MainWindow$4.intervalAdded(MainWindow.java:912)
	at javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:148)
	at javax.swing.DefaultListModel.add(DefaultListModel.java:481)
	at com.rarchives.ripme.ui.MainWindow$RipButtonHandler.actionPerformed(MainWindow.java:1276)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Unable to find title at https://www.8muses.com/comics/album/JAB-Comics/Vanilla
Using album title '8muses_JAB-Comics'

**Comment by cyian-1756** [comment]
I can't reproduce this
