### ISSUE TITLE
Ripping sporadically stops.

### ISSUE THREAD

**Issue by madhatr** [RipMeApp/ripme#1357]
* Ripme version: 1.7.85 Also at least the last 5 versions.
* Java version: 
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
* Operating system: Version 1806 build 17134.829
* Many different reddit users.
* Please include any additional information about how to reproduce the problem:
Start rip on roughly 1050 reddit users and 1 sub.
## Expected Behavior
Rips everything.

## Actual Behavior
Stops ripping on a download and never continues until I hit stop and rip again, at which point  it continues happily.

Here is a log capture of where is stopped today at 09:39, and where i hit stop and start when I returned home at 15:04, no log entry was made. 
"2019-06-28 09:39:02,087 DEBUG ripper.AbstractRipper .setWorkingDir() Using album title 'reddit_sub_labiagw'
2019-06-28 09:39:02,087 DEBUG ripper.AbstractRipper .setWorkingDir() Set working directory to: C:\Users\***\Desktop\RipMe\rips\reddit_sub_labiagw
2019-06-28 15:04:45,994 DEBUG ripper.AbstractRipper .getRipper() Found album ripper: com.rarchives.ripme.ripper.rippers.RedditRipper
2019-06-28 15:04:45,995 DEBUG ripper.AbstractRipper .setWorkingDir() Using album title 'reddit_user_Doodlebug94'"

I rip only reddit.
I've seen this happen many times over the last few months.   Sometimes it will rip everything just fine and another time it does not. 

Special case which I noted is when I add a new URL to rip and it decides to stop before finishing on the new URL, it does not add the URL to the history. Should I open a separate bug for this if one is not already open?

I'm going to run this java -jar \where\you\put\ripme.jar and see what I get.  Will wait out for more instructions.

Thanks for the  amazing software.

**Comment by cyian-1756** [comment]
I can't test this without a url

**Comment by madhatr** [comment]
I provided both logs, they both had urls in them?   I'm assuming its 

> [+] Saved http://i.imgur.com/wbEeFpA.jpg as .\rips\reddit_user_the_strawberry_slut\Veri_f_ication_post_Tell_me_what_you_think\8vfngt002-wbEeFpA.jpg

that's all the  logs show, how am i supposed to show a url?  if you mean the what url is in the the history its https://www.reddit.com/user/the_strawberry_slut

**Comment by madhatr** [comment]
It has just stopped again, and both logs show nothing this time.  URL I think is this https://www.reddit.com/user/secretlittle

log file
``2019-07-01 19:59:05,093 DEBUG ripper.AbstractRipper .getRipper() Found album ripper: com.rarchives.ripme.ripper.rippers.RedditRipper
2019-07-01 19:59:05,093 DEBUG ripper.AbstractRipper .setWorkingDir() Using album title 'reddit_user_secretlittle'
2019-07-01 19:59:05,093 DEBUG ripper.AbstractRipper .setWorkingDir() Set working directory to: C:\Users\Slithandor\Desktop\RipMe\rips\reddit_user_secretlittle

cmd output

> Checking http://imgur.com/aa1PsLL
Checking http://imgur.com/a/s3TSF
Fetching imgur album at http://imgur.com/a/s3TSF
    Retrieving http://imgur.com/a/s3TSF/all
Got imgur image: http://i.imgur.com/cTVHPLV.jpg
Got imgur image: http://i.imgur.com/9sAUP3k.jpg
Got imgur image: http://i.imgur.com/neFfUhV.jpg
Waiting for threads to finish

**Comment by madhatr** [comment]
Here is another one.   I think URL is http://i.imgur.com/jKA70sp.jpg from ripping https://www.reddit.com/user/hot-soccer-mom

> Downloading http://i.imgur.com/jKA70sp.jpg to C:\Users\*****\Desktop\RipMe\rips\reddit_user_hot-soccer-mom\A_tame_verification_post_f_or_starters....\a3amh5001-jKA70sp.jpg
[+] Creating directory: .\rips\reddit_user_hot-soccer-mom\A_tame_verification_post_f_or_starters
Writing http://i.imgur.com/jKA70sp.jpg to file
Exception:
java.io.IOException: Bad pathname
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(Unknown Source)
        at java.io.File.getCanonicalPath(Unknown Source)
        at com.rarchives.ripme.utils.Utils.removeCWD(Utils.java:291)
        at com.rarchives.ripme.ripper.DownloadFileThread.<init>(DownloadFileThread.java:48)
        at com.rarchives.ripme.ripper.AlbumRipper.addURLToDownload(AlbumRipper.java:81)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:344)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:348)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:352)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:370)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:289)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:193)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
        at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
        at java.lang.Thread.run(Unknown Source)
    Downloading file: http://i.imgur.com/jKA70sp.jpg Retry #1
Request properties: {Cookie=[], Referer=[https://imgur.com/a/HE8QPm2], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
Exception in thread "pool-2-thread-23" java.lang.NullPointerException
        at com.rarchives.ripme.ripper.DownloadFileThread.run(DownloadFileThread.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
url: http://i.imgur.com/XFez1AM.jpg, prefix: a3amh5002-, subdirectoryA tame verification post [f]or starters...., referrer: https://imgur.com/a/HE8QPm2, cookies: null, fileName: null
Downloading http://i.imgur.com/XFez1AM.jpg to C:\Users\****\Desktop\RipMe\rips\reddit_user_hot-soccer-mom\A_tame_verification_post_f_or_starters....\a3amh5002-XFez1AM.jpg
Writing http://i.imgur.com/XFez1AM.jpg to file
Exception:
java.io.IOException: Bad pathname
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(Unknown Source)
        at java.io.File.getCanonicalPath(Unknown Source)
        at com.rarchives.ripme.utils.Utils.removeCWD(Utils.java:291)
        at com.rarchives.ripme.ripper.DownloadFileThread.<init>(DownloadFileThread.java:48)
        at com.rarchives.ripme.ripper.AlbumRipper.addURLToDownload(AlbumRipper.java:81)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:344)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:348)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:352)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:370)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:289)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:193)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
        at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
        at java.lang.Thread.run(Unknown Source)
    Downloading file: http://i.imgur.com/XFez1AM.jpg Retry #1
Request properties: {Cookie=[], Referer=[https://imgur.com/a/HE8QPm2], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
Exception in thread "pool-2-thread-24" java.lang.NullPointerException
        at com.rarchives.ripme.ripper.DownloadFileThread.run(DownloadFileThread.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
url: http://i.imgur.com/RA9sEwO.jpg, prefix: a3amh5003-, subdirectoryA tame verification post [f]or starters...., referrer: https://imgur.com/a/HE8QPm2, cookies: null, fileName: null
Downloading http://i.imgur.com/RA9sEwO.jpg to C:\Users\****\Desktop\RipMe\rips\reddit_user_hot-soccer-mom\A_tame_verification_post_f_or_starters....\a3amh5003-RA9sEwO.jpg
Writing http://i.imgur.com/RA9sEwO.jpg to file
Exception:
java.io.IOException: Bad pathname
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(Unknown Source)
        at java.io.File.getCanonicalPath(Unknown Source)
        at com.rarchives.ripme.utils.Utils.removeCWD(Utils.java:291)
        at com.rarchives.ripme.ripper.DownloadFileThread.<init>(DownloadFileThread.java:48)
        at com.rarchives.ripme.ripper.AlbumRipper.addURLToDownload(AlbumRipper.java:81)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:344)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:348)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:352)
        at com.rarchives.ripme.ripper.AbstractRipper.addURLToDownload(AbstractRipper.java:370)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:289)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:193)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
        at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
        at java.lang.Thread.run(Unknown Source)
    Downloading file: http://i.imgur.com/RA9sEwO.jpg Retry #1
Request properties: {Cookie=[], Referer=[https://imgur.com/a/HE8QPm2], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
Exception in thread "pool-2-thread-25" java.lang.NullPointerException
        at com.rarchives.ripme.ripper.DownloadFileThread.run(DownloadFileThread.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Waiting for threads to finish
Found album ripper: com.rarchives.ripme.ripper.rippers.RedditRipper

**Comment by madhatr** [comment]
Here today again.  Another cmd out put log.

> Checking http://imgur.com/WVNdpzv
    Downloading file: https://i.imgur.com/qyaG1Zz.jpg Retry #1
Request properties: {Cookie=[], Referer=[http://imgur.com/qyaG1Zz], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
[!] Error
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://imgur.com/WVNdpzv
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:475)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:170)
        at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:150)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:260)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:193)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
        at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
        at java.lang.Thread.run(Unknown Source)
[!] Unable to rip URL: http://imgur.com/WVNdpzv
Checking http://imgur.com/a/k6wpJ
Fetching imgur album at http://imgur.com/a/k6wpJ
    Retrieving http://imgur.com/a/k6wpJ/all
[+] Saved https://i.imgur.com/qyaG1Zz.jpg as .\rips\reddit_user_gingersgonewild\cpjlngz--qyaG1Zz.jpg
Waiting for threads to finish
Found album ripper: com.rarchives.ripme.ripper.rippers.RedditRipper

After i hit stop it duplicates the last line.

> Found album ripper: com.rarchives.ripme.ripper.rippers.RedditRipper

**Comment by keokitsune** [comment]
i have the same problem, i have a list of reddits ill set to download over night but when i check in the morning maybe only 2 will have downloaded, some times the program is locked up but usually if i press stop then start it continues so i have to constantly baby sit the program for it to work. all other sites iv downloaded from work fine its just reddit.    

and it isnt consistent on what subreddit it happens on, it seems completely random, sometimes it will go though a particular subreddit fine while other times it will hang, and its random were it hangs within the download progress, sometimes its a few donloads in other times its in the middle or near the end.

**Comment by madhatr** [comment]
You might be able to find a solution,  this URL(below) will not process, usually you can just stop and re add but this one  breaks it every single time(3 times).  Thread error

https://www.reddit.com/user/Satans666Cheerleader/

`Checking https://v.redd.it/6m4p9hgflsa31
url: https://v.redd.it/6m4p9hgflsa31/DASH_1080 file: F:\RipMe\rips\reddit_user_Satans666Cheerleader\ce83ec-6m4p9hgflsa31-Super small village right beside pillager base if anyone is looking for a really good hardcore world/challenge. Seed is -9177657258166102818 and the video begins at the spawn point-.mp4
Checking https://i.redd.it/pmycjt2a55a31.jpg
Found single URL: https://i.redd.it/pmycjt2a55a31.jpg
    Downloading file: https://v.redd.it/6m4p9hgflsa31/DASH_1080 Retry #1
Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
Status code: 200
Exception in thread "pool-18-thread-1" java.lang.NullPointerException
        at com.rarchives.ripme.ripper.DownloadFileThread.run(DownloadFileThread.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Checking https://i.redd.it/u830tnfx4f831.jpg
Found single URL: https://i.redd.it/u830tnfx4f831.jpg
Found album ripper: com.rarchives.ripme.ripper.rippers.RedditRipper
Checking https://i.redd.it/kawjzi1ks5731.jpg
Found single URL: https://i.redd.it/kawjzi1ks5731.jpg
Checking https://i.redd.it/u4skju6hnw631.jpg
Found single URL: https://i.redd.it/u4skju6hnw631.jpg
Checking https://i.redd.it/mycokwc2m3631.jpg
Found single URL: https://i.redd.it/mycokwc2m3631.jpg
Checking https://i.redd.it/gsvg48jrc1631.jpg
Found single URL: https://i.redd.it/gsvg48jrc1631.jpg
Checking https://i.redd.it/j71hati1bb531.jpg
Found single URL: https://i.redd.it/j71hati1bb531.jpg
Checking https://i.redd.it/1ox3qcpux9431.jpg
Found single URL: https://i.redd.it/1ox3qcpux9431.jpg
Checking https://i.redd.it/x93cwzssso231.jpg
Found single URL: https://i.redd.it/x93cwzssso231.jpg
Checking https://i.redd.it/lutg4hg43s131.jpg
Found single URL: https://i.redd.it/lutg4hg43s131.jpg
Checking https://i.redd.it/i91opleboyx21.jpg
Found single URL: https://i.redd.it/i91opleboyx21.jpg
Waiting for threads to finish`

**Comment by madhatr** [comment]
I may have partially solved this issue. Hopefully it is not some new issue i noticed.  Anyway.  Today I noticed the reddit rips that are getting stuck at (97%, 99%, 93%) are all reddit users I typed in manually. Here is a few of them. So far no stops on URLS that were copied and pasted from the users link.

https://www.reddit.com/user/thediggitydank
http://reddit.com/user/Lilbekkah101
http://reddit.com/user/SaraMillsSecret
https://reddit.com/user/AnonymousWilder
http://www.reddit.com/user/LolaGirl18

Okay after copying and pasting them, i'm not so sure because thediggitydank is a full proper reddit url, but you'll notice the others are all either missing the 's' on https or missing the 'www',  Maybe it can help at lease.    I'll wait till the rest(1400) get ripped and edit in the rest that stop.
