### ISSUE TITLE
Instagram No images found at

### ISSUE THREAD

**Issue by bzrrr** [RipMeApp/ripme#1380]
* Ripme version:v1.7.85
* Java version: 'java -1.8'
* Operating system: 'winver'

* Exact URL you were trying to rip when the problem occurred:https://www.instagram.com/ruda__s2/
* Please include any additional information about how to reproduce the problem:
cant downloading
## Expected Behavior

download all images

## Actual Behavior

java.io.IOException: No images found at https://www.instagram.com/ruda__s2/
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:73)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xarantolus** [comment]
This happens with any private instagram account. You can however use the `instagram.session_id` setting in [the rip.properties file](https://github.com/RipMeApp/ripme/wiki/Config-options#to-change-these-option-on-your-ripme-install-edit-the-ripproperties-file) to log in ripme.

If you are logged into instagram in your browser, search for the `sessionid` cookie<sup>[1](https://github.com/RipMeApp/ripme/blob/bd58568821f6601bcc0c80a6a537df2615403e89/src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java#L37)</sup> and set it in the config file.

**Comment by trees-smoke** [comment]
Is it worth noting that the setting works but isn't documented in the linked page?

**Comment by cyian-1756** [comment]
> but isn't documented in the linked page?

Woops, looks like I forgot to update the wiki
