### ISSUE TITLE
DeviantArt Error / New UI

### ISSUE THREAD

**Issue by hi5kba** [RipMeApp/ripme#1385]
* Ripme version: 1.7.86
* Java version: Version 8 update 221 (build 1.8.0_221-b11)
* Operating system: Windows 10 Enterprise (i use Enterprise cuz i dislike microsoft's new policy on how they treat home / professional users in regards to update management and Administration)

## Expected Behavior

To Download from DeviantArt

## Actual Behavior

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

_Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_nukababe_gallery_adoptables-and-bases
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_kuoh-academy
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_side-characters
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_sitri-clan
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_phenex-clan
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_fallen-angels
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_hero
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_humans
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_multicharacter
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_uncensored
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_events
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_collaboration
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_rias-gremory
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_akeno-himejima
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_rossweisse
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_xenovia-quarta
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_asia-argento
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_koneko-toujou
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_irina-shidou
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_grayfia-lucifuge
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_kuroka
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_venelana-gremory
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_serafall-leviathan
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_ophis
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_highschooldxdcards_gallery_momo-momozono
null
Rip complete, saved to F:\PICTURES\pixiv\TMP\DxD Fallen Angels 231\HighschoolDxDCards\deviantart_nukababe_gallery_adoptables-and-bases
null_

URLS
![URLs](https://user-images.githubusercontent.com/33358741/62009305-a92ac600-b155-11e9-9ba2-df18c59d550c.png)

Possible Reason: New UI
![New UI](https://user-images.githubusercontent.com/33358741/62009313-ca8bb200-b155-11e9-9278-296c4eb56cdd.png)

**Comment by rautamiekka** [comment]
That must be Eclipse, the new format they've been working on for ages. I'm still on the old one.

**Comment by hi5kba** [comment]
Damn. i Already hate it! While i admit i like the cleaner design.....
the Rest is half-arsed.
don't get me started on the new "Core Member only Features"..........
Seems like they're using the excuse of new layout to restrict more commonly used features to Paying users.

While im on it Replying the Logs and that
[Per Gallery Logs](https://drive.google.com/open?id=10p_CEs0Knsjdeq1Ug-LcL29D4JAe4-LV)
[ripme.log](https://github.com/RipMeApp/ripme/files/3439354/ripme.log)

**Comment by UnforeseenOcean** [comment]
DeviantART downloader is busted, PhotoBucket and some ArtStation pages also fail to download with various errors.

**Comment by UnforeseenOcean** [comment]
Weirdly it works for a bit, then it suddenly starts spewing nulls and dying. The user favorite lists often work, but the artist pages often fail.

**Comment by UnforeseenOcean** [comment]
```
2019-08-04 21:17:10,857 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.DeviantartRipper.login(DeviantartRipper.java:188)
	at com.rarchives.ripme.ripper.rippers.DeviantartRipper.getFirstPage(DeviantartRipper.java:129)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:86)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.lang.Thread.run(Unknown Source)
```
This is the error that was recorded.

**Comment by metaprime** [comment]
[Mega-Thread] DeviantArt ripper is broken; yes we know -- de-duping all other DeviantArt issues to this one. https://github.com/RipMeApp/ripme/issues/2063
