### ISSUE TITLE
Only first 17 pictures of Instagram are getting ripped

### ISSUE THREAD

**Issue by thinkpad4** [RipMeApp/ripme#1397]
* Ripme version: 1.7.86
* Java version:  V8 update 221
* Operating system: Win7 64bit

* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/taylorswift/?hl=en
* Please include any additional information about how to reproduce the problem:
The ripper isn't pulling all the photos and videos from the page, only the first couple
## Expected Behavior
To get ALL the images and videos on a page
Detail the expected behavior here.

## Actual Behavior
Shows rip complete after only a few images no matter how many times I have it recheck ripped
Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by jerrycarlson** [comment]
Same/similar problem here.  Running same versions of Java and RipMe as OP, but I'm on Win10 x64.  I'm only getting first 13-37 items (varying numbers of images/videos) downloading from Instagram.

**Comment by phuthokx** [comment]
same here

**Comment by Ectomind1990** [comment]
I don't have this. Just did taylorswift and got back as far as 2018-12-25_13-14-05_Brz8RGUFHKq_47691216_131077937901870_3401986935164549264_n.jpg (132 files) before I decided to abort it

v1.7.86
Linux
openjdk version "1.8.0_222"
maximum download threads: 1
Timeout 60000

Maybe post logs

**Comment by jerrycarlson** [comment]
Very strange.  Based on Ectomind's comment I re-ran ripme on my Instagram list just now, and all URLs are back to retrieving full account rips (up to 1,712 files, in one case).

I haven't changed any software or settings on my computer or network/Internet connection since the time of my previous comment, so I have to assume the original problem came from Instagram's end.

**Comment by thinkpad4** [comment]
Yeah it seems to be getting them all again, strange.  What do you think, should I close this or leave it open incase the issue comes back?

**Comment by jerrycarlson** [comment]
*shrugs*  I would probably vote to close it, since we can't replicate the issue on our end anymore.

**Comment by Ectomind1990** [comment]
Got it!
Happened on https://www.instagram.com/montoyatwinz/
Within like 2 minutes I tried taylorswift and got it there as well. It's a java.io.EOFException from com.rarchives.ripme.ripper.rippers.InstagramRipper.graphqlRequest(InstagramRipper.java:246)
But there is no error shown in ripme UI so you think it worked ok. It just says Rip complete in green text.

Less than 3 minutes later I tried taylorswift again and the problem was gone. Then tried montoyatwinz again and the problem was gone there also

**Comment by Ectomind1990** [comment]
`2019-08-11 07:45:54,869 DEBUG ripper.AbstractRipper .sleep() Sleeping 2500ms
2019-08-11 07:45:58,329 WARN  utils.Http .response() Error while loading https://www.instagram.com/graphql/query/?query_hash=f2405b236d85e8296cf30347c9f08c2a&variables={"id":"11830955","after":"QVFDc1Q3MGduREhVZTlUU18xa3lqV0d0SHZOMU93ZjN5ZUlvblNTVTBPTnh2Vl93b2dsdnczOWVOejYySlpqU2t5bXRBb0xmckJmeTlab0pVVXU4V2RhZg==","first":12}
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:494)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.utils.Http.getJSON(Http.java:120)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.graphqlRequest(InstagramRipper.java:246)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getNextPage(InstagramRipper.java:212)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:92)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.lang.Thread.run(Thread.java:748)
2019-08-11 07:45:58,362 INFO  ripper.AbstractRipper .rip() Can't get next page: Failed to load https://www.instagram.com/graphql/query/?query_hash=f2405b236d85e8296cf30347c9f08c2a&variables={"id":"11830955","after":"QVFDc1Q3MGduREhVZTlUU18xa3lqV0d0SHZOMU93ZjN5ZUlvblNTVTBPTnh2Vl93b2dsdnczOWVOejYySlpqU2t5bXRBb0xmckJmeTlab0pVVXU4V2RhZg==","first":12} after 1 attempts
2019-08-11 07:45:58,375 DEBUG ripper.AbstractRipper .waitForThreads() Waiting for threads to finish
`

**Comment by Ectomind1990** [comment]
Where it says 'after 1 attempts' is that because my Retry download count is at 1?
```
download.retries = 1
```

**Comment by cyian-1756** [comment]
> Where it says 'after 1 attempts' is that because my Retry download count is at 1?

AFAIK yes.

> 2019-08-11 07:45:58,329 WARN  utils.Http .response() Error while loading https://www.instagram.com/graphql/query/?query_hash=f2405b236d85e8296cf30347c9f08c2a&variables={"id":"11830955","after":"QVFDc1Q3MGduREhVZTlUU18xa3lqV0d0SHZOMU93ZjN5ZUlvblNTVTBPTnh2Vl93b2dsdnczOWVOejYySlpqU2t5bXRBb0xmckJmeTlab0pVVXU4V2RhZg==","first":12}

Looks like there was some network errors while loading.

**Comment by thinkpad4** [comment]
@cyian-1756 you can close this or if you want I can, since it seems the problem went away.  It can always be reopened if the problem comes back

**Comment by cyian-1756** [comment]
@thinkpad4 I think we should close this issue and open a new one for the UI not reporting the error
