### ISSUE TITLE
Instagram download not working

### ISSUE THREAD

**Issue by errorlog90** [RipMeApp/ripme#1444]
* Ripme version:1.7.87
* Java version: java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
* Operating system: Microsoft Windows [Version 10.0.18362.356]

* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/lenameyerlandrut/?hl=de
* Please include any additional information about how to reproduce the problem

## Actual Behavior
2019-10-04 09:27:00,161 WARN  utils.Http .response() Error while loading https://www.instagram.com//www.instagram.com/static/bundles/metro/ProfilePageContainer.js/b88319511c6f.js
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://www.instagram.com//www.instagram.com/static/bundles/metro/ProfilePageContainer.js/b88319511c6f.js
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getQhash(InstagramRipper.java:186)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getFirstPage(InstagramRipper.java:141)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:55)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.lang.Thread.run(Unknown Source)
2019-10-04 09:27:00,397 WARN  utils.Http .response() Error while loading https://www.instagram.com//www.instagram.com/static/bundles/metro/ProfilePageContainer.js/b88319511c6f.js
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://www.instagram.com//www.instagram.com/static/bundles/metro/ProfilePageContainer.js/b88319511c6f.js
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getQhash(InstagramRipper.java:186)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getFirstPage(InstagramRipper.java:141)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:55)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.lang.Thread.run(Unknown Source)
[log.txt](https://github.com/RipMeApp/ripme/files/3689461/log.txt)

**Comment by tamenrip** [comment]
Same error on 1.7.92. All Instagram URLs affected. OS X 10.13.3. Jar Launcher 15.0.1 using JavaAppletPlugin 1.8.111.14.
