### ISSUE TITLE
Deviant Art and ArtStation ripping is not working

### ISSUE THREAD

**Issue by AlexFiala** [RipMeApp/ripme#1454]
* Ripme version: v1.7.88
* Java version:  v 8 update 181 
* Operating system:  Windows 10 Professional x64

https://www.artstation.com/vincentchu
AND
https://www.deviantart.com/yupachu/gallery/

## Expected Behavior
Detail the expected behavior here.
Both galleries download (note each gallery download is attempted separately).

## Actual Behavior
**Artstation**
![image](https://user-images.githubusercontent.com/24661916/66664367-6471df80-ec1a-11e9-92fb-585b7f52bc3a.png)

**Deviant Art**
![image](https://user-images.githubusercontent.com/24661916/66664430-81a6ae00-ec1a-11e9-988c-06c4458f05e1.png)

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Artstation Log**
no log entry is made, simply a "couldn't load JSON" message is returned.

**Deviant Art Log**
Downloading https://www.deviantart.com/yupachu/gallery/
Rip complete, saved to D:\Rippers\RIPS\deviantart_yupachu_gallery_featured
null

**Comment by darealmafu** [comment]
The error with deviantart appears to be during login. Originally I thought the account would have been banned, but I recompiled it with my own login information and got the same error. I'm not very good at programming, but this error log should help anyone that decides to fix the deviantart ripper: 

java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.DeviantartRipper.login(DeviantartRipper.java:188)
	at com.rarchives.ripme.ripper.rippers.DeviantartRipper.getFirstPage(DeviantartRipper.java:129)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.lang.Thread.run(Thread.java:748)

**Comment by onesimpleclik** [comment]
this has been broken for quite some time, hopefully someone can fix it

**Comment by heinrichI** [comment]
I want to fix it, but I cannot build the project in Eclipse. Who can help?

**Comment by astomi** [comment]
This issue was previously resolved for **URL_TYPE.SINGLE_PROJECT**; however, this was not reflected for the **URL_TYPE.USER_PORTFOLIO**.

java.io.IOException: Error fetching json. Status code:403

https://github.com/astomi/ripme/blob/b63a80fa4976cf5394a06f2e314506ac0e32dca0/src/main/java/com/rarchives/ripme/ripper/rippers/ArtStationRipper.java#L302-L321

**Comment by astomi** [comment]
I'll have it fixed in a few minutes. With some much needed refactoring: ```if (status / 100 == 2)```

**Comment by Tush-r** [comment]
> 
> 
> This issue was previously resolved by adding a user agent.
> 
> java.io.IOException: Error fetching json. Status code:403
> 
> https://github.com/astomi/ripme/blob/b63a80fa4976cf5394a06f2e314506ac0e32dca0/src/main/java/com/rarchives/ripme/ripper/rippers/ArtStationRipper.java#L302-L321

ArtStation issues are due the cloudflare page, so it may or may not work. 
I'll look into it.

**Comment by metaprime** [comment]
[Mega-Thread] DeviantArt ripper is broken; yes we know -- de-duping all other DeviantArt issues to this one. https://github.com/RipMeApp/ripme/issues/2063
