### ISSUE TITLE
Gfycat Error 403

### ISSUE THREAD

**Issue by ExodusHour** [RipMeApp/ripme#1480]
* Ripme version: 1.7.89
* Java version: 1.8.0_231
* Operating system: Windows 10.0.18362.418

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:
Trying to rerip only the urls from these profiles using cmd throws HTTP error fetching URL. Status=403. When trying to rerip the urls from the program it says rip completed but urls.txt doesn't download. I have a windows batch file that rerips the urls and downloads the urls.txt through youtube-dl every 6 hours. 

https://gfycat.com/@flames
https://gfycat.com/@brandonedora
https://gfycat.com/@Blueones
https://gfycat.com/@myblindy
https://gfycat.com/@TriangledCircle
https://gfycat.com/@Lester2031
https://gfycat.com/@Chuytlatelpa711
https://gfycat.com/@momopeach
https://gfycat.com/@Dang
https://gfycat.com/@masterf
https://gfycat.com/@djmolar
https://gfycat.com/@LethalBlu
https://gfycat.com/@golbanstorage

## Expected Behavior

Rerip the profile and download url.txt

## Actual Behavior

```
Initialized ripme v1.7.89
Loading history from C:\Users\joshj\AppData\Local\ripme\history.json
Retrieving https://gfycat.com/@flames
Error while loading https://api.gfycat.com/v1/users/flames/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/flames/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@flames
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/flames/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/flames/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@brandonedora
Error while loading https://api.gfycat.com/v1/users/brandonedora/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/brandonedora/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@brandonedora
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/brandonedora/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/brandonedora/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@Blueones
Error while loading https://api.gfycat.com/v1/users/Blueones/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/Blueones/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@Blueones
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/Blueones/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/Blueones/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@myblindy
Error while loading https://api.gfycat.com/v1/users/myblindy/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/myblindy/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@myblindy
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/myblindy/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/myblindy/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@TriangledCircle
Error while loading https://api.gfycat.com/v1/users/TriangledCircle/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/TriangledCircle/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@TriangledCircle
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/TriangledCircle/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/TriangledCircle/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@Lester2031
Error while loading https://api.gfycat.com/v1/users/Lester2031/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/Lester2031/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@Lester2031
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/Lester2031/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/Lester2031/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@Chuytlatelpa711
Error while loading https://api.gfycat.com/v1/users/Chuytlatelpa711/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/Chuytlatelpa711/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@Chuytlatelpa711
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/Chuytlatelpa711/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/Chuytlatelpa711/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@momopeach
Error while loading https://api.gfycat.com/v1/users/momopeach/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/momopeach/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@momopeach
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/momopeach/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/momopeach/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@Dang
Error while loading https://api.gfycat.com/v1/users/Dang/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/Dang/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@Dang
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/Dang/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/Dang/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@masterf
Error while loading https://api.gfycat.com/v1/users/masterf/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/masterf/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@masterf
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/masterf/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/masterf/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@djmolar
Error while loading https://api.gfycat.com/v1/users/djmolar/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/djmolar/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@djmolar
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/djmolar/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/djmolar/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@LethalBlu
Error while loading https://api.gfycat.com/v1/users/LethalBlu/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/LethalBlu/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@LethalBlu
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/LethalBlu/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/LethalBlu/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
Retrieving https://gfycat.com/@golbanstorage
Error while loading https://api.gfycat.com/v1/users/golbanstorage/gfycats
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/golbanstorage/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
[!] Failed to rip URL https://gfycat.com/@golbanstorage
java.io.IOException: Failed to load https://api.gfycat.com/v1/users/golbanstorage/gfycats after 1 attempts
        at com.rarchives.ripme.utils.Http.response(Http.java:137)
        at com.rarchives.ripme.utils.Http.get(Http.java:110)
        at com.rarchives.ripme.ripper.rippers.GfycatRipper.getFirstPage(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:94)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.handleArguments(App.java:183)
        at com.rarchives.ripme.App.main(App.java:78)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.gfycat.com/v1/users/golbanstorage/gfycats
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at com.rarchives.ripme.utils.Http.response(Http.java:130)
        ... 6 more
```

**Comment by felixaufreisen** [comment]
Either I don't understand what you're trying to do or I can't reproduce the error.

Can you explain a bit more detailed what you're trying to do?

**Comment by ExodusHour** [comment]
I'm running a rerip of only urls in cmd with java -jar ripme.jar -r

**Comment by ExodusHour** [comment]
I just tested it again and it seems to be working now
