### ISSUE TITLE
I'm receiving this error while ripping from a reddit user

### ISSUE THREAD

**Issue by vexyl13** [RipMeApp/ripme#1603]
2020-03-15 23:53:32,717 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
org.json.JSONException: JSONObject["video"] not found.
	at org.json.JSONObject.get(JSONObject.java:473)
	at org.json.JSONObject.getJSONObject(JSONObject.java:573)
	at com.rarchives.ripme.ripper.rippers.GfycatRipper.getVideoURL(GfycatRipper.java:152)
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:70)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:260)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleBody(RedditRipper.java:214)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:184)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:98)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:73)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.lang.Thread.run(Unknown Source)

[log.txt](https://github.com/RipMeApp/ripme/files/4335828/log.txt)

**Comment by pornismuybae** [comment]
What was the url you were trying to rip?

**Comment by XargonWan** [comment]
Same issue here, the problem is that after this error is not recovering and all the rip is stucking, can at least a skip be added?

`org.json.JSONException: JSONObject["video"] not found.
        at org.json.JSONObject.get(JSONObject.java:573)
        at org.json.JSONObject.getJSONObject(JSONObject.java:766)
        at com.rarchives.ripme.ripper.rippers.RedgifsRipper.getVideoURL(RedgifsRipper.java:195)
        at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:83)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:270)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:203)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:106)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:81)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.ripURL(App.java:296)
        at com.rarchives.ripme.App.handleArguments(App.java:265)
        at com.rarchives.ripme.App.main(App.java:78)
`
