### ISSUE TITLE
fuskator.com no longer works

### ISSUE THREAD

**Issue by MrSoloRojo** [RipMeApp/ripme#1676]
* Ripme version:
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred:
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The program to pull full sized images, like it had done in the past.

## Actual Behavior

It gives the error "No images found at" in red text. Here's a SFW gallery. 

https://fuskator.com/thumbs/cB4hWHsH7X8/index.html

Be mindful that a gallery by default shows thumbnails. Full sized images are available by clicking on the link on the page.

**Comment by ringofyre** [comment]
Can confirm. Log attached.

`2020-06-25 02:10:49,063 ERROR ripper.AbstractRipper .getURLsFromPage() Couldnt fetch images.
2020-06-25 02:10:49,066 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.io.IOException: No images found at https://fuskator.com/expanded/ghpM3fqPQnP/Nonnude-Babe-Nia-Nacci-from-FTV.html
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:124)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.lang.Thread.run(Unknown Source)`
