### ISSUE TITLE
InstagramRipper fails to rip anything

### ISSUE THREAD

**Issue by ULBAZOR** [RipMeApp/ripme#1719]
* Ripme version: 1.7.93
* Java version: 8 update 261 (1.8.0_261)
* Operating system: Windows 10 Version 2004 (19041.388)
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/instagram/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

I expected a full and complete rip of the posts on the account I was trying to rip.

## Actual Behavior

No post was ripped and I received an error which said "Error: null".

**Comment by thisisbobdole** [comment]
https://github.com/RipMeApp/ripme/issues/1699 Might be related to this, most of us are just finding it failing after ripping about one page of pics.

**Comment by thisisbobdole** [comment]
And now I am experience this exact same issue, getting a Error:null instead of anything.

**Comment by monney** [comment]
Getting the same issue

**Comment by monney** [comment]
Here's my full error printout

```
[+] Creating directory: ./rips/instagram_instagram
Retrieving https://www.instagram.com/instagram/
name:1:0 Expected an operand but found <
<!DOCTYPE html>
^
name:2:0 Expected an operand but found <
<html lang="en" class="no-js not-logged-in client-root">
^
name:3:4 Expected an operand but found <
    <head>
    ^
name:4:8 Expected an operand but found <
        <meta charset="utf-8">
        ^
name:5:8 Expected an operand but found <
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        ^
name:7:8 Expected an operand but found <
        <title>
        ^
name:9:1 Expected an operand but found /
</title>
 ^
name:12:8 Expected an operand but found <
        <meta name="robots" content="noimageindex, noarchive">
        ^
name:13:8 Expected an operand but found <
        <meta name="apple-mobile-web-app-status-bar-style" content="default">
        ^
name:14:8 Expected an operand but found <
        <meta name="mobile-web-app-capable" content="yes">
        ^
name:15:8 Expected an operand but found <
        <meta name="theme-color" content="#ffffff">
        ^
name:16:8 Expected an operand but found <
        <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover">
        ^
name:17:8 Expected an operand but found <
        <link rel="manifest" href="/data/manifest.json">
        ^
name:19:8 Expected an operand but found <
        <link rel="preload" href="/static/bundles/metro/ConsumerUICommons.css/e059ec4278a3.css" as="style" type="text/css" crossorigin="anonymous" />
        ^
name:20:0 Expected an operand but found <
<link rel="preload" href="/static/bundles/metro/ConsumerAsyncCommons.css/e5f471a37be6.css" as="style" type="text/css" crossorigin="anonymous" />
^
name:21:0 Expected an operand but found <
<link rel="preload" href="/static/bundles/metro/Consumer.css/2f3d4843da28.css" as="style" type="text/css" crossorigin="anonymous" />
^
name:22:0 Expected an operand but found <
<link rel="preload" href="/static/bundles/metro/LandingPage.css/8d927d69de86.css" as="style" type="text/css" crossorigin="anonymous" />
^
name:23:0 Expected an operand but found <
<link rel="preload" href="/static/bundles/metro/Vendor.js/5a56d51ae30f.js" as="script" type="text/javascript" crossorigin="anonymous" />
^
name:24:0 Expected an operand but found <
<link rel="preload" href="/static/bundles/metro/en_US.js/283c814fe246.js" as="script" type="text/javascript" crossorigin="anonymous" />
^
name:25:0 Expected an operand but found <
<link rel="preload" href="/static/bundles/metro/ConsumerLibCommons.js/8306c406d4b1.js" as="script" type="text/javascript" crossorigin="anonymous" />
^
name:26:0 Expected an operand but found <
<link rel="preload" href="/static/bundles/metro/ConsumerUICommons.js/ff9c759d0dbe.js" as="script" type="text/javascript" crossorigin="anonymous" />
^
name:27:0 Expected an operand but found <
<link rel="preload" href="/static/bundles/metro/ConsumerAsyncCommons.js/af02b1aebf9f.js" as="script" type="text/javascript" crossorigin="anonymous" />
^
name:28:0 Expected an operand but found <
<link rel="preload" href="/static/bundles/metro/Consumer.js/5aadc3e477b5.js" as="script" type="text/javascript" crossorigin="anonymous" />
^
name:29:0 Expected an operand but found <
<link rel="preload" href="/static/bundles/metro/LandingPage.js/b341e37926f3.js" as="script" type="text/javascript" crossorigin="anonymous" />
^
name:30:8 Expected an operand but found <
        <link rel="prefetch" as="script" href="/static/bundles/metro/FeedPageContainer.js/4589b7562b04.js" type="text/javascript" crossorigin="anonymous" />
        ^
name:31:0 Expected an operand but found <
<link rel="prefetch" as="stylesheet" href="/static/bundles/metro/FeedPageContainer.css/ca57a913952e.css" type="text/css" crossorigin="anonymous" />
^
name:34:8 Expected an operand but found <
        <script type="text/javascript">
        ^
name:41:0 Expected an operand but found <
</script>
^
name:42:8 Expected an operand but found <
        <script type="text/javascript">
        ^
name:132:0 Expected an operand but found <
</script><script type="text/javascript">
^
name:151:0 Expected an operand but found <
</script>
^
name:153:16 Expected an operand but found <
                <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/static/images/ico/apple-touch-icon-76x76-precomposed.png/666282be8229.png">
                ^
name:154:16 Expected an operand but found <
                <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/static/images/ico/apple-touch-icon-120x120-precomposed.png/8a5bd3f267b1.png">
                ^
name:155:16 Expected an operand but found <
                <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/static/images/ico/apple-touch-icon-152x152-precomposed.png/68193576ffc5.png">
                ^
name:156:16 Expected an operand but found <
                <link rel="apple-touch-icon-precomposed" sizes="167x167" href="/static/images/ico/apple-touch-icon-167x167-precomposed.png/4985e31c9100.png">
                ^
name:157:16 Expected an operand but found <
                <link rel="apple-touch-icon-precomposed" sizes="180x180" href="/static/images/ico/apple-touch-icon-180x180-precomposed.png/c06fdb2357bd.png">
                ^
name:159:20 Expected an operand but found <
                    <link rel="icon" sizes="192x192" href="/static/images/ico/favicon-192.png/68d99ba29cc8.png">
                    ^
name:163:20 Expected an operand but found <
                    <link rel="mask-icon" href="/static/images/ico/favicon.svg/fc72dd4bfde8.svg" color="#262626">
                    ^
name:165:18 Expected an operand but found <
                  <link rel="shortcut icon" type="image/x-icon" href="/static/images/ico/favicon.ico/36b3ee2d91ed.ico">
                  ^
name:171:0 Expected an operand but found <
<meta property="al:ios:app_name" content="Instagram" />
^
name:172:0 Expected an operand but found <
<meta property="al:ios:app_store_id" content="389801252" />
^
name:173:0 Expected an operand but found <
<meta property="al:ios:url" content="instagram://mainfeed" />
^
name:174:0 Expected an operand but found <
<meta property="al:android:app_name" content="Instagram" />
^
name:175:0 Expected an operand but found <
<meta property="al:android:package" content="com.instagram.android" />
^
name:176:0 Expected an operand but found <
<meta property="al:android:url" content="https://www.instagram.com/_n/mainfeed/" />
^
name:178:0 Expected an operand but found <
<meta property="og:site_name" content="Instagram" />
^
name:179:0 Expected an operand but found <
<meta property="og:title" content="Instagram" />
^
name:180:0 Expected an operand but found <
<meta property="og:image" content="/static/images/ico/favicon-200.png/ab6eff595bb1.png" />
^
name:181:0 Expected an operand but found <
<meta property="fb:app_id" content="124024574287414" />
^
name:182:0 Expected an operand but found <
<meta property="og:url" content="https://instagram.com/" />
^
name:183:0 Expected an operand but found <
<meta content="Create an account or log in to Instagram - A simple, fun &amp; creative way to capture, edit &amp; share photos, videos &amp; messages with friends &amp; family." name="description" />
^
name:184:0 Expected an operand but found <
<link rel="canonical" href="https://www.instagram.com/" />
^
name:187:4 Expected an operand but found <
    <link rel="alternate" href="https://www.instagram.com/" hreflang="x-default" />
    ^
name:188:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=en" hreflang="en" />
^
name:189:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=fr" hreflang="fr" />
^
name:190:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=it" hreflang="it" />
^
name:191:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=de" hreflang="de" />
^
name:192:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=es" hreflang="es" />
^
name:193:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=zh-cn" hreflang="zh-cn" />
^
name:194:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=zh-tw" hreflang="zh-tw" />
^
name:195:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=ja" hreflang="ja" />
^
name:196:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=ko" hreflang="ko" />
^
name:197:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=pt" hreflang="pt" />
^
name:198:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=pt-br" hreflang="pt-br" />
^
name:199:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=af" hreflang="af" />
^
name:200:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=cs" hreflang="cs" />
^
name:201:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=da" hreflang="da" />
^
name:202:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=el" hreflang="el" />
^
name:203:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=fi" hreflang="fi" />
^
name:204:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=hr" hreflang="hr" />
^
name:205:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=hu" hreflang="hu" />
^
name:206:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=id" hreflang="id" />
^
name:207:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=ms" hreflang="ms" />
^
name:208:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=nb" hreflang="nb" />
^
name:209:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=nl" hreflang="nl" />
^
name:210:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=pl" hreflang="pl" />
^
name:211:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=ru" hreflang="ru" />
^
name:212:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=sk" hreflang="sk" />
^
name:213:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=sv" hreflang="sv" />
^
name:214:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=th" hreflang="th" />
^
name:215:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=tl" hreflang="tl" />
^
name:216:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=tr" hreflang="tr" />
^
name:217:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=hi" hreflang="hi" />
^
name:218:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=bn" hreflang="bn" />
^
name:219:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=gu" hreflang="gu" />
^
name:220:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=kn" hreflang="kn" />
^
name:221:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=ml" hreflang="ml" />
^
name:222:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=mr" hreflang="mr" />
^
name:223:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=pa" hreflang="pa" />
^
name:224:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=ta" hreflang="ta" />
^
name:225:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=te" hreflang="te" />
^
name:226:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=ne" hreflang="ne" />
^
name:227:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=si" hreflang="si" />
^
name:228:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=ur" hreflang="ur" />
^
name:229:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=vi" hreflang="vi" />
^
name:230:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=bg" hreflang="bg" />
^
name:231:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=fr-ca" hreflang="fr-ca" />
^
name:232:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=ro" hreflang="ro" />
^
name:233:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=sr" hreflang="sr" />
^
name:234:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=uk" hreflang="uk" />
^
name:235:0 Expected an operand but found <
<link rel="alternate" href="https://www.instagram.com/?hl=zh-hk" hreflang="zh-hk" />
^
java.lang.NullPointerException
[!] Error while ripping URL https://www.instagram.com/instagram/
java.lang.NullPointerException
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.rangeError(ECMAErrors.java:266)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.rangeError(ECMAErrors.java:238)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.rangeError(ECMAErrors.java:225)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ErrorManager.checkLimit(ErrorManager.java:82)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ErrorManager.error(ErrorManager.java:149)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.handleParseException(Parser.java:472)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:327)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.Parser.parse(Parser.java:285)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getJsBodyBlock(InstagramRipper.java:449)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getHashValue(InstagramRipper.java:417)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getProfileHash(InstagramRipper.java:201)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getQhash(InstagramRipper.java:193)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getFirstPage(InstagramRipper.java:153)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:63)
	at com.rarchives.ripme.App.rip(App.java:103)
	at com.rarchives.ripme.App.ripURL(App.java:296)
	at com.rarchives.ripme.App.handleArguments(App.java:279)
	at com.rarchives.ripme.App.main(App.java:78)
```

**Comment by thinkpad4** [comment]
Yep, getting Error:null when trying to rip instagram

**Comment by Dler666** [comment]
+1

**Comment by soloturn** [comment]
is anonymous access a problem now?

**Comment by studioloft** [comment]
Same issue here...

**Comment by Tush-r** [comment]
I'll take a look at it and see if I can fix it.

**Comment by swaglogger** [comment]
I quickly glanced over 

> 

> 	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getQhash(InstagramRipper.java:193)

What does this?
`qHash = getQhash(document);` at 
https://github.com/RipMeApp/ripme/blob/master/src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java#L153


I was able to resolve this locally by hard setting qHash = "";
But I am not sure what this would affect just a temp solution

**Comment by UnforeseenOcean** [comment]
Same issue found here, all of the Instagram links error out with "null"

**Comment by Tush-r** [comment]
> 
> 
> I quickly glanced over
> 
> > 
> 
> > at com.rarchives.ripme.ripper.rippers.InstagramRipper.getQhash(InstagramRipper.java:193)
> 
> What does this?
> `qHash = getQhash(document);` at
> https://github.com/RipMeApp/ripme/blob/master/src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java#L153
> 
> I was able to resolve this locally by hard setting qHash = "";
> But I am not sure what this would affect just a temp solution

The way the IG ripper works is, it fetches `.js` files it needs, parses them and extracts the `queryHash` from it. Setting `qHash=""` should get rid of the current error but, the ripper should run into errors in the further steps. You do need the `queryHash` to rip the images.

You can check #1722 for a more detailed answer( and possibly some kind of fix).

**Comment by MetroDCGuy** [comment]
I'm getting the null issue too

**Comment by cariah** [comment]
> 
> 
> I'll take a look at it and see if I can fix it.

I've been working on something tonight, but it's pretty late and I need to test this a bit more before PR'ing. ( and sleep:] ) It's an updated Ripper, Nashorn (deprecated Java 11 I believe?) -> GraalVM.js to support the latest ECMAScript version to parse for the qHash. Changed a bit of the logic to choose which `js` file to parse as well.

Let me know what your thoughts are on adding a dependency to support parsing the newer ES versions.

**Comment by AranciataExcess** [comment]
Getting the null error with IG rips

**Comment by yothrowawaytoday** [comment]
I've been getting null like everyone else, but I just tried again today, and I was able to rip. Can anyone else confirm?

**Comment by thinkpad4** [comment]
@yothrowawaytoday Still not working for me.  Waiting for @cyian-1756 to release/push a fix

**Comment by menial717** [comment]
> I've been getting null like everyone else, but I just tried again today, and I was able to rip. Can anyone else confirm?
> 
> EDIT: It sorta works. For new profile rips, it only downloads the first page. I tried with https://www.instagram.com/alexandradaddario/

Yep, now getting the same result. Varies from 19 to 30 images only

**Comment by AranciataExcess** [comment]
Still getting null error (v1.7.93)

**Comment by thinkpad4** [comment]
@cariah are you able to compile ripme with your IG fix in it until @cyian-1756 pushes out a official version?  I don't know how to compile it myself or I would.  Thank you very much

**Comment by Kirmakoff** [comment]
@thinkpad4 
I've build the @cariah fixed version using maven for Windows 10 x64. It fixed the issue and worked fine for me!
Here is the link, all credit goes to @cariah : 
https://drive.google.com/file/d/123MGXJaJEFNemzS59BAK1h0hMgkYkyqs/view?usp=sharing

**Comment by thinkpad4** [comment]
@Kirmakoff SWEET, thank you so much, this will help hold me over until @cyian-1756 pushes the fix into the main program.

**Comment by AranciataExcess** [comment]
Thanks I'll use that build!

**Comment by menial717** [comment]
The problem seems to have reared its ugly head again. Had been using the new build perfectly until last night. 

Just tried now ripping a few new insta accounts and the new build is suddenly only downloading the first 15-30 images.

**Comment by ANaPhOrAX** [comment]
can confirm, fix doesn't work anymore

**Comment by thinkpad4** [comment]
Anyone find a way to get IG working again?

**Comment by AranciataExcess** [comment]
Must be another IG change, it's only ripping page one.

**Comment by menial717** [comment]
As posted in the other thread i got 37 images downloaded from an account yesterday with the new release before it stopped working again. Tried again today on a different account - this time 67 images before I got the "no images found" error.

Has anyone else managed to get it working?

**Comment by cyian-1756** [comment]
@menial717 

> Has anyone else managed to get it working?

I ripped a few accounts to completetion before pushing the update, maybe it's rate limiting on IG's side? If so I'll edit the wait times and push an update

**Comment by 89z** [comment]
same error
