### ISSUE TITLE
Instagram ripper can't find next pages, doesn't rip past first page

### ISSUE THREAD

**Issue by Malkierian** [RipMeApp/ripme#1781]
* Ripme version: 
1.7.93
* Java version: 
openjdk version "14.0.1" 2020-04-14
* Operating system: 
Windows 10 20H2
* Exact URL you were trying to rip when the problem occurred:
https://www.instagram.com/kimkyejung016/
https://www.instagram.com/kimune5531/
https://www.instagram.com/heart_art___/

## Expected Behavior
Download all files.

## Actual Behavior
Downloads only first page. Doesn't matter if it's a re-rip or a new rip. I also have the rip_after_already_seen option disabled in my config (with a # in front of it, though I just tested with removing the line completely as well), and they're all public accounts, so it doesn't even matter if my session_id is good or not (which it is, I just checked before sending this in).

**Comment by winb1g** [comment]
Ripme Ver:
1.7.93
Java version:
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Operating system:
Windows 10 1909

Also experiencing this issue. Cannot download specific highlights either.
https://www.instagram.com/frankprisinzano/
https://www.instagram.com/stories/highlights/17865687110131554/

**Comment by agtpirrone** [comment]
Here to bump on this issue..

Ripme version: 1.7.93
Java version: Java(TM) SE Runtime Environment (build 12.0.1+12)
Operating system: Microsoft Windows [Versión 10.0.19041.572] (2004)

Examples:
https://www.instagram.com/dronenerds/
https://www.instagram.com/paisajesargentinosok/

**Comment by purplepandapants** [comment]
I'm also having the same issue. Downloads only rip the first page.

Also, not sure if it's the same or different issue but the folder with the user Instagram images sometimes disappears once the rip is complete.

**Comment by taurhel** [comment]
fix is WIP here
https://github.com/taurhel/ripme/blob/master/src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
now it can rip multiple pages but I want to verify additionally

**Comment by Malkierian** [comment]
Downloaded and built, can confirm this fixed it for me, currently on 260 completed of a third rip past 30 or so.

**Comment by Malkierian** [comment]
OK, I got to 556 and got this error: A JSONObject text must begin with '{' at 1 [character 2 line 1]
It wasn't done yet. The last time I had ripped this account was March 5, and this only got to August 12 from now. Then, I closed it to remove the end rip after seen option to rerip, and all it tells me is "null" and doesn't download anything.

**Comment by WK328** [comment]
Non-coder here, thanks to everyone for their hard work.

Is there a simple way to take the link above and convert it to a working jar? I'm willing to test it out if I can find out the process.

**Comment by gitdine** [comment]
After updating to 1.7.94 the Instagram ripper worked perfectly for a while and downloaded everything. But after a couple of uses suddenly stopped working entirely, now nothing is downloaded. I have a feeling my IP got action blocked from too much activity but I'm not certain, has anyone else had this issue? This is the log output:

> 2020-11-24 04:30:59,865 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.io.IOException: No images found at https://www.instagram.com/XXX
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:81)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.lang.Thread.run(Thread.java:748)

**Comment by WK328** [comment]
> 
> 
> After updating to 1.7.94 the Instagram ripper worked perfectly for a while and downloaded everything. But after a couple of uses suddenly stopped working entirely, now nothing is downloaded. I have a feeling my IP got action blocked from too much activity but it could also bug with the app, has anyone else had this issue? This is the log output:
> 
> > 2020-11-24 04:30:59,865 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
> > java.io.IOException: No images found at https://www.instagram.com/retroscifiart/
> > at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:81)
> > at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
> > at java.lang.Thread.run(Thread.java:748)

it stopped working for me after only 2 accounts also, and they mentioned the issue on the official reddit...

**Comment by Malkierian** [comment]
I had the same issue. Just turn down your download thread count. I did it to 5 and haven't had an issue since. BTW you'll have to reactivate your account through the app or the browser in order to unblock, if you have it tied to an account session.

**Comment by Malkierian** [comment]
Well, nevermind, I just got another suspension this morning.
