### ISSUE TITLE
allporncomics doesn't work for me anymore

### ISSUE THREAD

**Issue by leftnutofThanos** [RipMeApp/ripme#1791]
* Ripme version: v1.7.93
* Java version: Version 8 Update 271
* Operating system: Windows 10 Version 1909
* Exact URL you were trying to rip when the problem occurred: https://allporncomic.com/porncomic/meet-the-neighbors-rabies-t-lagomorph/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Pics from the gallery should queue and download. 

## Actual Behavior

I get a red error at the top sayig "Error: no protocol:". I have tried to download the comics individually but the same result shows. I have not downloaded the comics before. Other valid websites still work, but allporncomics has recently shown this error.

Downloading https://allporncomic.com/porncomic/meet-the-neighbors-rabies-t-lagomorph/
Rip complete, saved to C:\Users\aqibn\OneDrive\Documents\rips\allporncomic_meet-the-neighbors-rabies-t-lagomorph
Downloading https://allporncomic.com/porncomic/meet-the-neighbors-rabies-t-lagomorph/2-meet-the-neighbors/
Rip complete, saved to C:\Users\aqibn\OneDrive\Documents\rips\allporncomic_meet-the-neighbors-rabies-t-lagomorph_2-meet-the-neighbors
no protocol: 
Downloading https://allporncomic.com/porncomic/meet-the-neighbors-rabies-t-lagomorph/1-meet-the-neighbors/
Rip complete, saved to C:\Users\aqibn\OneDrive\Documents\rips\allporncomic_meet-the-neighbors-rabies-t-lagomorph_1-meet-the-neighbors
no protocol: 
Downloading https://allporncomic.com/porncomic/meet-the-neighbors-rabies-t-lagomorph/0-meet-the-neighbors/
Rip complete, saved to C:\Users\aqibn\OneDrive\Documents\rips\allporncomic_meet-the-neighbors-rabies-t-lagomorph_0-meet-the-neighbors
no protocol:

**Comment by quietpenquin** [comment]
I am also getting the 'no protocol:' error. Here's an example error with debug messages:

Retrieving https://allporncomic.com/porncomic/the-hillbilly-farm-wc-tf/37-the-hillbilly-farm/
Found image url #1:
Got exception while running ripper:
java.net.MalformedURLException: no protocol:
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:130)
        at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
        at java.lang.Thread.run(Unknown Source)

**Comment by relister** [comment]
Having the same issue. No protocol error.

Navigating the site pages manually, I have noticed that they no longer displaying all the pics at once, instead release more at certain points as you navigate down the page. This is a new behavior.

**Comment by colosseus96** [comment]
Same problem here.. Hope the dev will fix this soon.
