### ISSUE TITLE
Doesn't like direct links to imgur images

### ISSUE THREAD

**Issue by PaulBGD** [RipMeApp/ripme#180]
```
❯ java -jar ../ripme.jar --url https://i.imgur.com/0irAxHr.jpg
Loaded file:/home/ripme/ripme.jar!/rip.properties
Loaded log4j.properties
Initialized ripme v1.6.10
[!] Error while ripping URL https://i.imgur.com/0irAxHr.jpg
java.lang.Exception: No compatible ripper found
        at com.rarchives.ripme.ripper.AbstractRipper.getRipper(AbstractRipper.java:371)
        at com.rarchives.ripme.App.rip(App.java:65)
        at com.rarchives.ripme.App.ripURL(App.java:177)
        at com.rarchives.ripme.App.handleArguments(App.java:169)
        at com.rarchives.ripme.App.main(App.java:56)
```

Also makes me wonder if ripme could attempt to download images directly if they have a .jpg/.png/.etc extension, but that's for another issue.

**Comment by cyian-1756** [comment]
At this point ripme can't download direct imgur images.

> Also  makes me wonder if ripme could attempt to download images directly if  they have a .jpg/.png/.etc extension, but that's for another issue.


I did some work on that in PR #78

**Comment by rautamiekka** [comment]
You're on a Linux, so use `wget` or `curl` to DL it.
