### ISSUE TITLE
Instagram No images found

### ISSUE THREAD

**Issue by madara19** [RipMeApp/ripme#1813]
hello
i have the latest version but i can't download from intagram

https://i.imgur.com/uNkdaED.png

**Comment by LP560** [comment]
Getting same error, it works 50% of the time

**Comment by grahammitchell** [comment]
I get this too for new albums, but 100% of the time.

```
Got exception while running ripper:
java.io.IOException: No images found at https://www.instagram.com/REDACTED/
        at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:81)
        at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by LP560** [comment]
Another thread #1802 mentions API being the cause possibly. But even on a first rip it'll fail sometimes or mid way through 
![2020-12-27_022951](https://user-images.githubusercontent.com/7595316/103471486-19784680-4d4f-11eb-85c6-3858caa366b3.png)
