### ISSUE TITLE
Disabled test: InstagramRipperTest#testInstagramAlbums -- fix and re-enable or remove

### ISSUE THREAD

**Issue by metaprime** [RipMeApp/ripme#185]
See #21

```
testInstagramAlbums(com.rarchives.ripme.tst.ripper.rippers.InstagramRipperTest)  Time elapsed: 0.521 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Failed to download a single file from http://instagram.com/anacheri
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.rarchives.ripme.tst.ripper.rippers.RippersTest.testRipper(RippersTest.java:33)
	at com.rarchives.ripme.tst.ripper.rippers.InstagramRipperTest.testInstagramAlbums(InstagramRipperTest.java:31)
```

**Comment by cyian-1756** [comment]
I'm not sure why this test is failing. If you try to rip http://instagram.com/anacheri it seems to work fine

**Comment by metaprime** [comment]
Apparently this test is one of the ones that works locally but not in Travis. Not sure why. See: https://github.com/RipMeApp/ripme/pull/213#issuecomment-345203624

**Comment by cyian-1756** [comment]
This has been fixed and re-enabled
