### ISSUE TITLE
Disabled test: VideoRippersTest#testVineRipper -- fix and re-enable or remove

### ISSUE THREAD

**Issue by metaprime** [RipMeApp/ripme#186]
See #21 

```
testVineRipper(com.rarchives.ripme.tst.ripper.rippers.VideoRippersTest)  Time elapsed: 0.269 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Error while ripping https://vine.co/v/hiqQrP0eUZx : java.io.IOException: Could not find meta property 'twitter:player:stream' at https://vine.co/v/hiqQrP0eUZx
	at junit.framework.Assert.fail(Assert.java:47)
	at com.rarchives.ripme.tst.ripper.rippers.VideoRippersTest.videoTestHelper(VideoRippersTest.java:31)
	at com.rarchives.ripme.tst.ripper.rippers.VideoRippersTest.testVineRipper(VideoRippersTest.java:62)
```

**Comment by cyian-1756** [comment]
I think the vine ripper should be removed at this point. The vine archive is broken as fall as I can tell and there's no talk of it ever getting fixed

**Comment by metaprime** [comment]
Can we not scrape vine.co itself?

**Comment by cyian-1756** [comment]
Vine.co doesn't host the videos anymore
