### ISSUE TITLE
doesn't download redgifs videos

### ISSUE THREAD

**Issue by buckssss** [RipMeApp/ripme#1866]
* Ripme version: 1.7.95
* Java version: java version "13" 2019-09-17
Java(TM) SE Runtime Environment (build 13+33)
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)
* Operating system: macOS 10.15.7
* Exact URL you were trying to rip when the problem occurred: https://www.reddit.com/r/hugeboobs/comments/n4n4bp/would_you_hire_me/
* Please include any additional information about how to reproduce the problem:
rip any reddit post with redgifs video attached
## Expected Behavior
download mp4 video

## Actual Behavior
DOESN'T download mp4 video

 java -jar ripme.jar -u https://www.reddit.com/r/hugeboobs/comments/n4n4bp/would_you_hire_me/
Loaded ……..rip.properties
Setting locale to en_US
Loaded log4j.properties
Initialized ripme v1.7.95
Loading history from ….history.json
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Retrieving https://redgifs.com/watch/everysandybrownbats
Trying to load cookies from config for redgifs.com
Exception while retrieving redgifs page:
java.io.IOException
	at com.rarchives.ripme.ripper.rippers.RedgifsRipper.getVideoURL(RedgifsRipper.java:198)
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:83)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:270)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:203)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:106)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:81)
	at com.rarchives.ripme.App.rip(App.java:103)
	at com.rarchives.ripme.App.ripURL(App.java:296)
	at com.rarchives.ripme.App.handleArguments(App.java:279)
	at com.rarchives.ripme.App.main(App.java:78)

**Comment by mykeehu** [comment]
Same problem here

**Comment by floopybird** [comment]
Same error on CentOS Linux 7.8. Something seems to have changed on the redgifs side of the equation in the last week or two.

-> java -jar ripme.jar -u https://www.reddit.com/r/hugeboobs/comments/n4n4bp/would_you_hire_me/
Loaded /home/foo/.config/ripme/rip.properties
Setting locale to en_US
Loaded log4j.properties
Initialized ripme v1.7.95
Loading history from /home/foo/.config/ripme/history.json
Trying to load cookies from config for www.reddit.com
Trying to load cookies from config for reddit.com
Retrieving https://redgifs.com/watch/everysandybrownbats
Trying to load cookies from config for redgifs.com
Exception while retrieving redgifs page:
java.io.IOException
        at com.rarchives.ripme.ripper.rippers.RedgifsRipper.getVideoURL(RedgifsRipper.java:198)
        at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:83)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:270)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:203)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:106)
        at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:81)
        at com.rarchives.ripme.App.rip(App.java:103)
        at com.rarchives.ripme.App.ripURL(App.java:296)
        at com.rarchives.ripme.App.handleArguments(App.java:279)
        at com.rarchives.ripme.App.main(App.java:78)

**Comment by floopybird** [comment]
@borderline232 any chance you're still around and can help figure this one out? Thank you for your previous work to implement the redgifs ripper!

**Comment by borderline232** [comment]
@floopybird Seems like someone added some cookies searching logic that's messing everything up. I'll try and find some time to fix the issue, but in the mean time I have a package on my fork of ripme (https://github.com/borderline232/ripme/releases) that works just fine (I hope), just make sure that when it prompts you if you want to update to a newer version choose no.

**Comment by JRussell** [comment]
> 
> 
> @floopybird Seems like someone added some cookies searching logic that's messing everything up. I'll try and find some time to fix the issue, but in the mean time I have a package on my fork of ripme (https://github.com/borderline232/ripme/releases) that works just fine (I hope), just make sure that when it prompts you if you want to update to a newer version choose no.

Your fork seems to do the same thing for me. The latest release you have posted is from Jan.

**Comment by borderline232** [comment]
@JRussell Ahh, I see the problem and I have the fix. I just want to implement ripping self posts and my fork should have the updated package up pretty soon.

**Comment by borderline232** [comment]
@JRussell ok it's up, let me know if there's any issues
