### ISSUE TITLE
vsco.co error

### ISSUE THREAD

**Issue by jeffkruczynski** [RipMeApp/ripme#1939]
Unable to download any vsco.com images

Mac: 1.7.95, java 1.8.0_302, Monterey 12.1. Any VSCO URL returns error: null.

Retrieving https://vsco.co/any profile here/gallery
 Trying to load cookies from config for vsco.co 
Trying to load cookies from config for vsco.co 
Trying to load cookies from config for vsco.co 
Could not get site id 
Trying to load cookies from config for vsco.co 
Could not profile images [!] 
Error while ripping URL https://vsco.co/any profile here/gallery
 java.lang.NullPointerException 
at com.rarchives.ripme.ripper.rippers.VscoRipper.getURLsFromPage(VscoRipper.java:87) 
at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:112) 
at com.rarchives.ripme.App.rip(App.java:103) at com.rarchives.ripme.App.ripURL(App.java:296) 
at com.rarchives.ripme.App.handleArguments(App.java:265) at com.rarchives.ripme.App.main(App.java:78)

**Comment by tbrtje** [comment]
For me the error is a different one, I get `Cannot invoke "org.json.JSONObject.getJSONArray(String)" because "this.profileJSON" is null` when trying to download anything from vsco

**Comment by goodboi69** [comment]
I just get a `null` error.

**Comment by soloturn** [comment]
this got fixed here: https://github.com/ripmeapp2/ripme/pull/59, see https://github.com/ripmeapp2/ripme/releases .
