### ISSUE TITLE
Suddenly stops downloading

### ISSUE THREAD

**Issue by oxinsstyle** [RipMeApp/ripme#1955]
* Ripme version: 1795
* Java version: java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) Client VM (build 25.311-b11, mixed mode)

* Operating system:  Windows 11 Home Insider Preview 22543.1000

* Exact URL you were trying to rip when the problem occurred: i have 200+ URL's i run.
* Please include any additional information about how to reproduce the problem: every 10 or 15 user data downloads (included folders) then it stops. no dead links

## Actual Behavior

Downloading multiple reddit user contents plus folders. after 10 user downloads it stops.

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: offset out of bounds
        at sun.util.locale.provider.RuleBasedBreakIterator.checkOffset(Unknown Source)
        at sun.util.locale.provider.RuleBasedBreakIterator.preceding(Unknown Source)
        at javax.swing.text.GlyphView.getBreakSpot(Unknown Source)
        at javax.swing.text.GlyphView.getBreakWeight(Unknown Source)
        at javax.swing.text.FlowView$LogicalView.getPreferredSpan(Unknown Source)
        at javax.swing.text.FlowView.calculateMinorAxisRequirements(Unknown Source)
        at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
        at javax.swing.text.BoxView.checkRequests(Unknown Source)
        at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
        at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
        at javax.swing.text.BoxView.checkRequests(Unknown Source)
        at javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
        at javax.swing.text.BoxView.layout(Unknown Source)
        at javax.swing.text.BoxView.setSize(Unknown Source)
        at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(Unknown Source)
        at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(Unknown Source)
        at javax.swing.JComponent.getPreferredSize(Unknown Source)
        at javax.swing.JEditorPane.getPreferredSize(Unknown Source)
        at javax.swing.text.JTextComponent.getPreferredScrollableViewportSize(Unknown Source)
        at javax.swing.ViewportLayout.preferredLayoutSize(Unknown Source)
        at java.awt.Container.preferredSize(Unknown Source)
        at java.awt.Container.getPreferredSize(Unknown Source)
        at javax.swing.JComponent.getPreferredSize(Unknown Source)
        at javax.swing.ScrollPaneLayout.preferredLayoutSize(Unknown Source)
        at java.awt.Container.preferredSize(Unknown Source)
        at java.awt.Container.getPreferredSize(Unknown Source)
        at javax.swing.JComponent.getPreferredSize(Unknown Source)
        at java.awt.GridBagLayout.GetLayoutInfo(Unknown Source)
        at java.awt.GridBagLayout.getLayoutInfo(Unknown Source)
        at java.awt.GridBagLayout.ArrangeGrid(Unknown Source)
        at java.awt.GridBagLayout.arrangeGrid(Unknown Source)
        at java.awt.GridBagLayout.layoutContainer(Unknown Source)
        at java.awt.Container.layout(Unknown Source)
        at java.awt.Container.doLayout(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validate(Unknown Source)
        at javax.swing.RepaintManager$3.run(Unknown Source)
        at javax.swing.RepaintManager$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Getting key tray.hide in nl_NL value Hide
Getting key tray.show in nl_NL value Show

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

it just stops.

**Comment by soloturn** [comment]
you mind trying https://github.com/ripmeapp2/ripme/releases ?

**Comment by 89z** [comment]
please provide example URL

**Comment by soloturn** [comment]
partially fixed. reopen with details if you have some pls
