### ISSUE TITLE
Unable to download twitter accounts

### ISSUE THREAD

**Issue by gemini0213** [RipMeApp/ripme#2021]
* Ripme version: 1.7.95
* Java version: 
* Operating system: 

* Exact URL you were trying to rip when the problem occurred: https://twitter.com/Susu_jpg but its the same for every twitter account.
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Just downloads straight away.

## Actual Behavior

Shows the following error
![save](https://user-images.githubusercontent.com/130473050/231180077-1e8e4d12-737f-4618-aede-4d68145cdef9.PNG)

**Comment by Nesjin** [comment]
Same issue with using Twitter, must be something Musk did with the API.

**Comment by gemini0213** [comment]
Hope it gets fixed soon.
Why can't these people just leave things the way they are.

**Comment by gemini0213** [comment]
> > Hope it gets fixed soon. Why can't these people just leave things the way they are.
> 
> Cause the person who bought twitter overpaid cause he's a moron and has been making bad decisions since.

Are there any other twitter downloaders you recommend?

**Comment by pr0525** [comment]
me neither..  maybe we can't download Twitter media for a while.

**Comment by the-jdr** [comment]
Thought it was just me! I definitely think something happened to the API. The coding has been messed with. Let's hope it comes back or there's a solution soon.

**Comment by gemini0213** [comment]
I wonder if the developer for ripme will reprogram the app to work with the new twitter API?
Seems like an app update was a long time ago.

**Comment by atmcoderr** [comment]
I have the same issue but with another application , elon musk probably changed something in the API

**Comment by linhaplana** [comment]
I've been using some browser extension ever since. It's not nearly as neat, but it works.

**Comment by medledan** [comment]
Guys this is a dead repo. Hasnt been updated in 2 years.

**Comment by gemini0213** [comment]
So is there anything we can do?

**Comment by the-jdr** [comment]
So uhhh I think the issue is the API. Apparently Elon made it not free or something along those lines. Breaking this. Or it could be something completely different. Idk my guess.

**Comment by eswiig** [comment]
I use hitomi to download twitter, you can import cookies.

**Comment by Ash-627** [comment]
> I use hitomi to download twitter, you can import cookies.

So, how do you keep it from redownloading the already downloaded files, and only download the updates?

**Comment by EinsteinIamNot** [comment]
cant download either since a while
here i have a log if that may help

2023-06-04 16:48:04,970 DEBUG ripper.DownloadThreadPool .initialize() Initializing Main thread pool with 5 threads
2023-06-04 16:48:04,973 INFO  ripper.AbstractRipper .rip() Retrieving https://twitter.com/hanasaki_hb01
2023-06-04 16:48:04,976 INFO  utils.Http .cookiesForURL() Trying to load cookies from config for api.twitter.com
2023-06-04 16:48:04,976 INFO  utils.Http .cookiesForURL() Trying to load cookies from config for twitter.com
2023-06-04 16:48:05,279 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.io.IOException: Failed to load https://api.twitter.com/oauth2/token: Status Code 403. You might be able to circumvent this error by setting cookies for this domain
	at com.rarchives.ripme.utils.Http.response(Http.java:193)
	at com.rarchives.ripme.utils.Http.post(Http.java:165)
	at com.rarchives.ripme.ripper.rippers.TwitterRipper.getAccessToken(TwitterRipper.java:86)
	at com.rarchives.ripme.ripper.rippers.TwitterRipper.getFirstPage(TwitterRipper.java:171)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:63)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:616)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://api.twitter.com/oauth2/token
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:459)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:180)
	... 6 more
2023-06-04 16:48:05,280 DEBUG ripper.AbstractRipper .waitForThreads() Waiting for threads to finish
2023-06-04 16:48:05,281 INFO  ripper.AbstractRipper .checkIfComplete()    Rip completed!
2023-06-04 16:48:05,282 DEBUG ripper.AbstractRipper .checkIfComplete() Changing log file back to 'ripme.log'
