### ISSUE TITLE
[SOLVED] RipMe Fails on Startup (Linux Kubuntu 22.04)

### ISSUE THREAD

**Issue by shadenegret** [RipMeApp/ripme#2037]
Hey, so I just switched over to Kubuntu 22.04.
And now when I wanna start-up RipMe it fails. Can anyone help?
I have JDK8 and 17.

Log:
```
hellhound-cafe@vivobook:~/Dokumente$ java -jar ripme.jar 
Loaded file:/home/hellhound-cafe/Dokumente/ripme.jar!/rip.properties
Setting locale to default
Loaded log4j.properties
Initialized ripme v1.7.95
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1388)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1386)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
        at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1423)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1397)
        at java.desktop/java.awt.Component.<clinit>(Component.java:624)
        at com.rarchives.ripme.ui.MainWindow.<init>(MainWindow.java:179)
        at com.rarchives.ripme.App.main(App.java:89)
```

**Comment by shadenegret** [comment]
Had to install JDK-11.. Works now.
