### ISSUE TITLE
GfycatRipper broken (website changed, probably)

### ISSUE THREAD

**Issue by metaprime** [RipMeApp/ripme#233]
* Ripme version: 1.6.13
* Java version: 1.8.0_151
* Operating system: Microsoft Windows [Version 10.0.15063]
* Exact URL you were trying to rip when the problem occurred: https://gfycat.com/gifs/detail/UnkemptCelebratedDonkey
* Please include any additional information about how to reproduce the problem: CLI or GUI both fail in the same way, but in this case I was trying to rip with the CLI.

## Expected Behavior

Rips the video

## Actual Behavior

```
E:\dev\ripme>java -jar ripme.jar -u https://gfycat.com/gifs/detail/UnkemptCelebratedDonkey
Loaded E:\dev\ripme\rip.properties
Loaded log4j.properties
Initialized ripme v1.6.13
Retrieving https://gfycat.com/gifs/detail/UnkemptCelebratedDonkey
[!] Error while ripping URL https://gfycat.com/gifs/detail/UnkemptCelebratedDonkey
java.io.IOException: Could not find source#mp4source at https://gfycat.com/gifs/detail/UnkemptCelebratedDonkey
        at com.rarchives.ripme.ripper.rippers.video.GfycatRipper.getVideoURL(GfycatRipper.java:70)
        at com.rarchives.ripme.ripper.rippers.video.GfycatRipper.rip(GfycatRipper.java:54)
        at com.rarchives.ripme.App.rip(App.java:67)
        at com.rarchives.ripme.App.ripURL(App.java:177)
        at com.rarchives.ripme.App.handleArguments(App.java:169)
        at com.rarchives.ripme.App.main(App.java:56)
```

**Comment by cyian-1756** [comment]
This was fixed in #377
