### ISSUE TITLE
Hentai-foundry errors on getNextPage

### ISSUE THREAD

**Issue by jacklollz2** [RipMeApp/ripme#406]
* Ripme version: 1.7.14
* Java version: 1.8.0_151-b12
* Operating system: Windows 10 1709 16299.192 64 bit
* Exact URL you were trying to rip when the problem occurred: Some Hentai foundry URLs.
Tested that give out errors: https://www.hentai-foundry.com/pictures/user/quaraci

* Please include any additional information about how to reproduce the problem: Attempt to download the Hentai foundry page.

## Expected Behavior
Files download successfully.

## Actual Behavior
Some files download but then the program gives out an error saying Null.

**Comment by cyian-1756** [comment]
The exact error ripme throws is 

```
Got exception while running ripper:
java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.HentaifoundryRipper.getNextPage(HentaifoundryRipper.java:77)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:129)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:472)
	at java.lang.Thread.run(Thread.java:748)
Waiting for threads to finish
```
