### ISSUE TITLE
Erome doesn't work

### ISSUE THREAD

**Issue by passtheball** [RipMeApp/ripme#449]
* Ripme version: 1.7.21
* Java version:  Java 8 Update 161
* Operating system:   Windows 10
* Exact URL you were trying to rip when the problem occurred: https://www.erome.com/a/tDI1vj3o
* Please include any additional information about how to reproduce the problem:  

Nothing happens when clicking rip

## Expected Behavior

Want to rip the album/webpage/profile of erome user/page

## Actual Behavior

Enter erome website then it shows "Erome album detected" then when I click rip nothing happens show a blank log page.

Shows this in the Ripme log:

java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.EromeRipper.getAlbumTitle(EromeRipper.java:50)
	at com.rarchives.ripme.ripper.AlbumRipper.setWorkingDir(AlbumRipper.java:196)
	at com.rarchives.ripme.ripper.AbstractRipper.setup(AbstractRipper.java:140)
	at com.rarchives.ripme.ui.MainWindow.ripAlbum(MainWindow.java:1074)
	at com.rarchives.ripme.ui.MainWindow.ripNextAlbum(MainWindow.java:1033)
	at com.rarchives.ripme.ui.MainWindow.access$600(MainWindow.java:69)
	at com.rarchives.ripme.ui.MainWindow$4.intervalAdded(MainWindow.java:794)
	at javax.swing.AbstractListModel.fireIntervalAdded(Unknown Source)
	at javax.swing.DefaultListModel.add(Unknown Source)
	at com.rarchives.ripme.ui.MainWindow$RipButtonHandler.actionPerformed(MainWindow.java:1108)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
2018-03-02 20:02:55,840 INFO  utils.Utils .saveConfig() Saved configuration to C:\Users

**Comment by cyian-1756** [comment]
I can't repo this on Ubuntu 16.02 with ripme 1.7.21

**Comment by passtheball** [comment]
What does can't repro mean

**Comment by passtheball** [comment]
Does can't repro mean cant reprogram it?

**Comment by cyian-1756** [comment]
It's means I can't reproduce it. I can rip the url https://www.erome.com/a/tDI1vj3o without getting any errors

**Comment by passtheball** [comment]
What do you suggest I do?
