### ISSUE TITLE
Tumblr Videos not downloading

### ISSUE THREAD

**Issue by SugarMrPoon** [RipMeApp/ripme#615]
* Ripme version:  1.7.47
* Java version: Java 8 Update 171
* Operating system: Mac OS X 10.13.4
* Exact URL you were trying to rip when the problem occurred:  All tumblrs, e.g. http://leaked-sextapes2.tumblr.com (NSFW!!)
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Running RipMe to save only Tumblr URLs to a text file (for deduplication reasons).  Historically, Image files (JPG, PNG, GIF) save first, then all video (MOV, MP4) last

## Actual Behavior

No Tumblr video file URLS are being captured.   When unselecting the "Save URLs only" option, video files are also not downloaded.   Historically this has worked fine.

**Comment by Benwebdev** [comment]
Second the tumblrs not working.

**Comment by SugarMrPoon** [comment]
As of 6:15pm PT, photos are also not downloading from Tumblr.

**Comment by erofanboy** [comment]
ava.net.MalformedURLException: unknown protocol: httpss
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at com.rarchives.ripme.ripper.rippers.TumblrRipper.handleJSON(TumblrRipper.java:248)
	at com.rarchives.ripme.ripper.rippers.TumblrRipper.rip(TumblrRipper.java:191)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:555)
	at java.lang.Thread.run(Unknown Source)

[log.txt](https://github.com/RipMeApp/ripme/files/2058413/log.txt)
