### ISSUE TITLE
Instagram downloads do not work after first page

### ISSUE THREAD

**Issue by phaelon74** [RipMeApp/ripme#619]
* Ripme version: v1.7.47
* Java version:  1.8.0_161
* Operating system:  - Windows 10 - Version 1803 (OS Build 17134.48)
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/amanda_blanks/
* Please include any additional information about how to reproduce the problem:
I downloaded several instagram pages yesterday without issue but now it's only downloading the first page and then rolling to Error: Null on EVERY instagram page I pull up.

## Expected Behavior
Download pictures from public instagram account until no more pictures remain

## Actual Behavior
The first page is downloaded, and then the program errors out in Null.

LOG:

Downloading next page
Downloading https://scontent-ort2-1.cdninstagram.com/5B937331/t51.2885-15/e35/32212306_113721072797558_1687967953154211840_n.jpg
https://scontent-ort2-1.cdninstagram.com/5B937331/t51.2885-15/e35/32212306_113721072797558_1687967953154211840_n.jpg : Non-retriable status code 403 while downloading https://scontent-ort2-1.cdninstagram.com/5B937331/t51.2885-15/e35/32212306_113721072797558_1687967953154211840_n.jpg
Rip complete, saved to C:\Users\thedude\Documents\CV\IG Rips\instagram_amanda_blanks
null

**Comment by Ectomind1990** [comment]
This is #608 but as you say, now it is happening every time for the last day or so, instead of intermittent. I commented the NullPointerException that you get in 1.7.47

I tried 1.7.46 and it still fails early but the error is different
```
Got exception while running ripper:
java.lang.IllegalArgumentException: Cookie value must not be null
	at org.jsoup.helper.Validate.notNull(Validate.java:26)
	at org.jsoup.helper.HttpConnection$Base.cookie(HttpConnection.java:295)
	at org.jsoup.helper.HttpConnection.cookies(HttpConnection.java:158)
	at com.rarchives.ripme.utils.Http.cookies(Http.java:87)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getNextPage(InstagramRipper.java:381)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:165)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:533)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Ectomind1990** [comment]
I would love to have a setting "wait at least this long before loading the next page". I am not in a hurry so I would set this to like N=30 seconds. Would be great if ripme fails to load a page this reason or any other reason it retries after 2N seconds (60 for me) and again after 4N and 8N and 16N

**Comment by phaelon74** [comment]
Thanks @Ectomind1990 .  I saw that thread and saw it was closed in the middle, so I was worried it was no longer open, so I created this one as well to make sure it got fully covered/reviewed.

**Comment by bored** [comment]
It seems to hang after the `NullPointerException`, here's the full stack trace for me:
```
~/Pictures
❯ java -jar ripme.jar -u https://www.instagram.com/amanda_blanks
Loaded /home/user/.config/ripme/rip.properties
Loaded log4j.properties
Initialized ripme v1.7.47
sanitized URL is https://www.instagram.com/amanda_blanks
Retrieving https://www.instagram.com/amanda_blanks
{}
Could not find query_hash on https://www.instagram.com/static/bundles/base/ProfilePageContainer.js/f38773cca89a.js
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/fbbb2bb2ff835c839b89d4f1a6fa5ef8/5B937331/t51.2885-15/e35/32212306_113721072797558_1687967953154211840_n.jpg Retry #1
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/5c623a7b8e15840a0bc013843ebeb4f6/5BA3218E/t51.2885-15/e35/32580405_2079627935659051_3800399814705807360_n.jpg Retry #1
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/6a35cb447c0b6cbc078e00b2b5f168bb/5B9012E5/t51.2885-15/e35/32063823_194923191159500_7907727368297381888_n.jpg Retry #1
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/8096e9059b8841cca3a3122df2883951/5BBDC532/t51.2885-15/e35/31997942_240221640073113_7471146395085307904_n.jpg Retry #1
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/6c8cc2a006d246b4359c5501036f4e0e/5BBFD29E/t51.2885-15/e35/32514463_599297900427691_1448195511159881728_n.jpg Retry #1
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/6a35cb447c0b6cbc078e00b2b5f168bb/5B9012E5/t51.2885-15/e35/32063823_194923191159500_7907727368297381888_n.jpg as ./rips/instagram_amanda_blanks/2018_05_23_08_14_32063823_194923191159500_7907727368297381888_n.jpg
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/f500e2441768deb391bb9d7087c15db5/5B84A674/t51.2885-15/e35/31939016_168685620457647_8193058212027564032_n.jpg Retry #1
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/6c8cc2a006d246b4359c5501036f4e0e/5BBFD29E/t51.2885-15/e35/32514463_599297900427691_1448195511159881728_n.jpg as ./rips/instagram_amanda_blanks/2018_05_21_07_21_32514463_599297900427691_1448195511159881728_n.jpg
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/5ba5a6388ce6162e64df04ddd57b3097/5B833ACE/t51.2885-15/e35/31973763_1014213825401162_5822324070946963456_n.jpg Retry #1
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/fbbb2bb2ff835c839b89d4f1a6fa5ef8/5B937331/t51.2885-15/e35/32212306_113721072797558_1687967953154211840_n.jpg as ./rips/instagram_amanda_blanks/2018_05_25_12_57_32212306_113721072797558_1687967953154211840_n.jpg
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/d23cb8ee30e16e62a1fa3fcbf47a9f78/5B84A832/t51.2885-15/e35/32162711_215515349230487_3030574910272438272_n.jpg Retry #1
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/8096e9059b8841cca3a3122df2883951/5BBDC532/t51.2885-15/e35/31997942_240221640073113_7471146395085307904_n.jpg as ./rips/instagram_amanda_blanks/2018_05_22_10_09_31997942_240221640073113_7471146395085307904_n.jpg
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/f8b82b260595c967bc01450869b0a8f6/5BC1DF3D/t51.2885-15/e35/31908746_178079429689544_7814538513688297472_n.jpg Retry #1
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/5c623a7b8e15840a0bc013843ebeb4f6/5BA3218E/t51.2885-15/e35/32580405_2079627935659051_3800399814705807360_n.jpg as ./rips/instagram_amanda_blanks/2018_05_23_10_13_32580405_2079627935659051_3800399814705807360_n.jpg
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/5ba5a6388ce6162e64df04ddd57b3097/5B833ACE/t51.2885-15/e35/31973763_1014213825401162_5822324070946963456_n.jpg as ./rips/instagram_amanda_blanks/2018_05_20_10_52_31973763_1014213825401162_5822324070946963456_n.jpg
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/f500e2441768deb391bb9d7087c15db5/5B84A674/t51.2885-15/e35/31939016_168685620457647_8193058212027564032_n.jpg as ./rips/instagram_amanda_blanks/2018_05_21_12_34_31939016_168685620457647_8193058212027564032_n.jpg
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/d23cb8ee30e16e62a1fa3fcbf47a9f78/5B84A832/t51.2885-15/e35/32162711_215515349230487_3030574910272438272_n.jpg as ./rips/instagram_amanda_blanks/2018_05_19_10_29_32162711_215515349230487_3030574910272438272_n.jpg
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/f8b82b260595c967bc01450869b0a8f6/5BC1DF3D/t51.2885-15/e35/31908746_178079429689544_7814538513688297472_n.jpg as ./rips/instagram_amanda_blanks/2018_05_17_10_01_31908746_178079429689544_7814538513688297472_n.jpg
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/a01d56cc0c9ad2f26d6386acb47c2aed/5BA414BF/t51.2885-15/e35/31556518_2088869978035852_3570263926409003008_n.jpg Retry #1
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/6796b63dd705115abbb99e4bafee7c7d/5B9E61D9/t51.2885-15/e35/32583930_179055079420649_3689267853749387264_n.jpg Retry #1
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/5e1aa278b960deece64f4392e5a5660a/5B94BE89/t51.2885-15/e35/32376453_228247771274762_7086059614441046016_n.jpg Retry #1
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/8e684f4dc75b03df050f10465244d8a8/5B9F4A1B/t51.2885-15/e35/31556477_2218604388179596_6608980904968716288_n.jpg Retry #1
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/1d3759dbc52e6d10e873dc1f736c92b8/5B839B9D/t51.2885-15/e35/32006457_766465240408349_2035920845989216256_n.jpg Retry #1
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/5e1aa278b960deece64f4392e5a5660a/5B94BE89/t51.2885-15/e35/32376453_228247771274762_7086059614441046016_n.jpg as ./rips/instagram_amanda_blanks/2018_05_16_12_07_Bi0VAmigLHm32376453_228247771274762_7086059614441046016_n.jpg
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/6fc0254fd22285a5396d50d5fd121e74/5B88968D/t51.2885-15/e35/31729565_178606596297024_4588006042658406400_n.jpg Retry #1
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/8e684f4dc75b03df050f10465244d8a8/5B9F4A1B/t51.2885-15/e35/31556477_2218604388179596_6608980904968716288_n.jpg as ./rips/instagram_amanda_blanks/2018_05_16_12_07_Bi0VAmigLHm31556477_2218604388179596_6608980904968716288_n.jpg
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/cc27fbc00939233bcafdd3175618fb0b/5BC12C22/t51.2885-15/e35/31412312_229938657587358_2779729389753991168_n.jpg Retry #1
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/6796b63dd705115abbb99e4bafee7c7d/5B9E61D9/t51.2885-15/e35/32583930_179055079420649_3689267853749387264_n.jpg as ./rips/instagram_amanda_blanks/2018_05_16_12_07_Bi0VAmigLHm32583930_179055079420649_3689267853749387264_n.jpg
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/vp/bde421bfddfb291f417cbaa7ad312e7f/5BC4E7D9/t51.2885-15/e35/31503981_1250198588416265_3207132198243139584_n.jpg Retry #1
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/cc27fbc00939233bcafdd3175618fb0b/5BC12C22/t51.2885-15/e35/31412312_229938657587358_2779729389753991168_n.jpg as ./rips/instagram_amanda_blanks/2018_05_14_10_43_31412312_229938657587358_2779729389753991168_n.jpg
    Downloading file: https://scontent-lhr3-1.cdninstagram.com/5B937331/t51.2885-15/e35/32212306_113721072797558_1687967953154211840_n.jpg Retry #1
71cf3b347bd27a018cc2da58b79d33ce
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/bde421bfddfb291f417cbaa7ad312e7f/5BC4E7D9/t51.2885-15/e35/31503981_1250198588416265_3207132198243139584_n.jpg as ./rips/instagram_amanda_blanks/2018_05_14_10_23_31503981_1250198588416265_3207132198243139584_n.jpg
[!] Non-retriable status code 403 while downloading from https://scontent-lhr3-1.cdninstagram.com/5B937331/t51.2885-15/e35/32212306_113721072797558_1687967953154211840_n.jpg
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/a01d56cc0c9ad2f26d6386acb47c2aed/5BA414BF/t51.2885-15/e35/31556518_2088869978035852_3570263926409003008_n.jpg as ./rips/instagram_amanda_blanks/2018_05_16_12_07_Bi0VAmigLHm31556518_2088869978035852_3570263926409003008_n.jpg
Unable to get query_hash
Server returned HTTP response code: 400 for URL: https://www.instagram.com/graphql/query/?query_hash=null&variables={"id":"19595844","first":50,"after":"1779000470560350848"}
[!] Error while ripping URL https://www.instagram.com/amanda_blanks
java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.pageHasImages(InstagramRipper.java:395)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getNextPage(InstagramRipper.java:377)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:85)
	at com.rarchives.ripme.App.rip(App.java:92)
	at com.rarchives.ripme.App.ripURL(App.java:250)
	at com.rarchives.ripme.App.handleArguments(App.java:237)
	at com.rarchives.ripme.App.main(App.java:67)
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/6fc0254fd22285a5396d50d5fd121e74/5B88968D/t51.2885-15/e35/31729565_178606596297024_4588006042658406400_n.jpg as ./rips/instagram_amanda_blanks/2018_05_16_12_07_Bi0VAmigLHm31729565_178606596297024_4588006042658406400_n.jpg
[+] Saved https://scontent-lhr3-1.cdninstagram.com/vp/1d3759dbc52e6d10e873dc1f736c92b8/5B839B9D/t51.2885-15/e35/32006457_766465240408349_2035920845989216256_n.jpg as ./rips/instagram_amanda_blanks/2018_05_16_12_07_Bi0VAmigLHm32006457_766465240408349_2035920845989216256_n.jpg
^C
~/Pictures 10m 8s
❯ 
```

**Comment by phaelon74** [comment]
Thanks @cyian-1756 .  Just downloaded the latest revision and it's working again, happy as can be.  Rocksauce!!
