### ISSUE TITLE
proxy with authentication not working

### ISSUE THREAD

**Issue by HalliHalloSchatz** [RipMeApp/ripme#660]
proxy with authentication not working

Initialized ripme v1.7.50
Retrieving https://raw.githubusercontent.com/ripmeapp/ripme/master/ripme.json
Error while fetching update:
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:449)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:170)
        at com.rarchives.ripme.ui.UpdateUtils.updateProgram(UpdateUtils.java:52)
        at com.rarchives.ripme.ui.MainWindow.lambda$upgradeProgram$1(MainWindow.java:201)
        at java.lang.Thread.run(Unknown Source)

**Comment by cyian-1756** [comment]
How are you authing to the proxy?

**Comment by HalliHalloSchatz** [comment]
proxy.http

String

HTTP Proxy (format [user:password]@host[:port]) WARNING: see https://stackoverflow.com/q/41505219 for HTTP Proxy with user/password

**Comment by cyian-1756** [comment]
This is because you're using https and the default settings of jdk 8, You have to edit the variables jdk.http.auth.tunneling.disabledSchemes and jdk.http.auth.proxying.disabledSchemes to blank like this:

jdk.http.auth.tunneling.disabledSchemes=
jdk.http.auth.proxying.disabledSchemes=


or run ripme with the flags `-Djdk.http.auth.tunneling.disabledSchemes="" -Djdk.http.auth.proxying.disabledSchemes=""` (So the end command would be `java -jar -Djdk.http.auth.tunneling.disabledSchemes="" -Djdk.http.auth.proxying.disabledSchemes="" ripme.jar)

**Comment by cyian-1756** [comment]
@HalliHalloSchatz 

Did you manage to get this working?

**Comment by cyian-1756** [comment]
@HalliHalloSchatz 

I going to close this as you've no responded, if this is still an issue leave a comment and I'll reopen it
