### ISSUE TITLE
Upcoming version of Ubuntu (17.10) breaks ripme because of removal of tray

### ISSUE THREAD

**Issue by emk2203** [RipMeApp/ripme#67]
* Ripme version: 1.5.7, also tested 1.5.0
* Java version: openjdk version "1.8.0_144"
* Operating system: Ubuntu 17.10
* Exact URL you were trying to rip when the problem occurred: <at startup of ripme>
* Please include any additional information about how to reproduce the problem:

Simply start with `java -jar ripme.jar`

## Expected Behavior

GUI of ripme should open

## Actual Behavior

```
$ java -jar src/ripme.jar 
Loaded /home/emk2203/rip.properties
Loaded log4j.properties
Initialized ripme v1.5.7
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.awt.TrayIcon.<init>(TrayIcon.java:144)
	at java.awt.TrayIcon.<init>(TrayIcon.java:168)
	at com.rarchives.ripme.ui.MainWindow.setupTrayIcon(MainWindow.java:947)
	at com.rarchives.ripme.ui.MainWindow.createUI(MainWindow.java:250)
	at com.rarchives.ripme.ui.MainWindow.<init>(MainWindow.java:164)
	at com.rarchives.ripme.App.main(App.java:51)

```
I suspect that the [reported tray icon removal in the new Ubuntu version](http://www.omgubuntu.co.uk/2017/09/will-you-miss-gnome-legacy-tray) is the problem here.

**Comment by cyian-1756** [comment]
This should be a pretty simple fix, just wrap tray UI code in a try catch

**Comment by rautamiekka** [comment]
I'm sorry for the spam, I'm just not really understanding GitHub, in an effort to avoid using Git's commands ...
