### ISSUE TITLE
Instagram site changed? giving org.json.JSONException: JSONObject["edge_owner_to_timeline_media"]

### ISSUE THREAD

**Issue by Ectomind1990** [RipMeApp/ripme#712]
* Ripme version: 1.7.52
* Java version: 1.8
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/kevin/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Download whole account, 1602 posts

## Actual Behavior

Only downloads first page, 13 files

```
2018-06-17 23:13:50,707 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
org.json.JSONException: JSONObject["edge_owner_to_timeline_media"] not found.
	at org.json.JSONObject.get(JSONObject.java:473)
	at org.json.JSONObject.getJSONObject(JSONObject.java:573)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.pageHasImages(InstagramRipper.java:395)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getNextPage(InstagramRipper.java:376)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:92)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:555)
	at java.lang.Thread.run(Thread.java:748)
2018-06-17 23:13:50,720 DEBUG ripper.AbstractRipper .waitForThreads() Waiting for threads to finish
```

I first saw this error 26 hours ago and since then I have got it every time

**Comment by cyian-1756** [comment]
Looks like a website change

**Comment by Stylite** [comment]
Is this going to get fixed soon?

**Comment by cyian-1756** [comment]
@Stylite 

> Is this going to get fixed soon?

I've fixed it and am pushing an update now

**Comment by cyian-1756** [comment]
@Stylite The update is live
