### ISSUE TITLE
Issue on 8muses

### ISSUE THREAD

**Issue by Fastmedic** [RipMeApp/ripme#730]
* Ripme version: 1.7.54
* Java version:  1.8.0_171
* Operating system: Win 10 V1803

* Exact URL you were trying to rip when the problem occurred(All Urls)
https://www.8muses.com/comics/album/Various-Authors/Boundless-Comics/Lookers/Issue-1

* Please include any additional information about how to reproduce the problem:
Enter URL press RIP.

## Expected Behavior
Download Images.

## Actual Behavior
Failed to Load *a URL* after 0 attempts

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

`2018-06-23 11:41:39,564 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.io.IOException: Failed to load https://www.8muses.com/comics/album/Various-Authors/Boundless-Comics/Lookers/Issue-1 after 0 attempts
	at com.rarchives.ripme.utils.Http.response(Http.java:137)
	at com.rarchives.ripme.ripper.rippers.EightmusesRipper.getFirstPage(EightmusesRipper.java:81)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:86)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:555)
	at java.lang.Thread.run(Unknown Source)
`

`2018-06-23 11:47:13,621 INFO  ui.MainWindow .loadHistory() Loading history from C:\Users\name\AppData\Local\ripme\history.json
2018-06-23 11:47:18,279 DEBUG ripper.AbstractRipper .getRipper() Found album ripper: com.rarchives.ripme.ripper.rippers.EightmusesRipper
2018-06-23 11:47:18,632 DEBUG ripper.AbstractRipper .getRipper() Found album ripper: com.rarchives.ripme.ripper.rippers.EightmusesRipper
2018-06-23 11:47:18,644 INFO  ripper.AbstractRipper .getAlbumTitle() Unable to find title at https://www.8muses.com/comics/album/Various-Authors/Boundless-Comics/Lookers/Issue-1
2018-06-23 11:47:18,644 DEBUG ripper.AbstractRipper .setWorkingDir() Using album title '8muses_Various-Authors'
2018-06-23 11:47:18,645 DEBUG ripper.AbstractRipper .setWorkingDir() Set working directory to: C:\Users\name\Downloads\rips\8muses_Various-Authors
2018-06-23 11:47:18,682 INFO  ripper.AbstractRipper .getAlbumTitle() Unable to find title at https://www.8muses.com/comics/album/Various-Authors/Boundless-Comics/Lookers/Issue-1
2018-06-23 11:47:20,089 INFO  utils.Utils .saveConfig() Saved configuration to C:\Users\name\AppData\Local\ripme\rip.properties
`

**Comment by cyian-1756** [comment]
This looks like a network issue on your end, can you load the site in a browser?

**Comment by Fastmedic** [comment]
Yes I can load it in a browser.  I am able to rip other sites fine as well, tested on imgur.  I also tested with VPN turned on in case they were blocking my IP.

**Comment by cyian-1756** [comment]
Is this still an issue?

**Comment by Fastmedic** [comment]
Yeah, still an issue.

**Comment by cyian-1756** [comment]
Have you tried using the latest version of ripme?

**Comment by Fastmedic** [comment]
Yes, I am on 1.7.65 now.

**Comment by cyian-1756** [comment]
Then I really have no idea what's wrong here. From the log it looks like ripme can't even connect to the internet. 

Maybe try ripping the http url instead of https, or running ripme as admin

**Comment by rephormat** [comment]
@cyian-1756 
Recommend closing:

1. Not Reproducible
2. Stale Issue
