### ISSUE TITLE
Adding the abillity to rip direct links?

### ISSUE THREAD

**Issue by nfrelink** [RipMeApp/ripme#750]
* Ripme version: 1.7.55
* Java version: openjdk version "1.8.0_171"
* Operating system: Linux Debian 9.4 Stretch

* Exact URL you were trying to rip when the problem occurred: N/A
* Please include any additional information about how to reproduce the problem: Rip a direct link instead of an album or page.

## Expected Behavior

Ripping direct links like i.imgur.com/blablabla.format successfully, or at least create a list of all the failed rips.

## Actual Behavior

Direct links get an error, and won't be downloaded. It would be useful if they would get downloaded too. Errors like these occur:  (NSFW link)
`Retrieving https://thumbs.gfycat.com/BareDisloyalCleanerwrasse-size_restricted.gif
Error while loading https://thumbs.gfycat.com/BareDisloyalCleanerwrasse-size_restricted.gif
org.jsoup.UnsupportedMimeTypeException: Unhandled content type. Must be text/*, application/xml, or application/xhtml+xml. Mimetype=image/gif, URL=https://thumbs.gfycat.com/BareDisloyalCleanerwrasse-size_restricted.gif
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:487)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.utils.Http.get(Http.java:110)
	at com.rarchives.ripme.ripper.rippers.video.GfycatRipper.getVideoURL(GfycatRipper.java:73)
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:61)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:229)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:170)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:102)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:77)
	at com.rarchives.ripme.App.rip(App.java:92)
	at com.rarchives.ripme.App.ripURL(App.java:258)
	at com.rarchives.ripme.App.handleArguments(App.java:228)
	at com.rarchives.ripme.App.main(App.java:67)
Exception while retrieving gfycat page:
java.io.IOException: Failed to load https://thumbs.gfycat.com/BareDisloyalCleanerwrasse-size_restricted.gif after 1 attempts
	at com.rarchives.ripme.utils.Http.response(Http.java:137)
	at com.rarchives.ripme.utils.Http.get(Http.java:110)
	at com.rarchives.ripme.ripper.rippers.video.GfycatRipper.getVideoURL(GfycatRipper.java:73)
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:61)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:229)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:170)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:102)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:77)
	at com.rarchives.ripme.App.rip(App.java:92)
	at com.rarchives.ripme.App.ripURL(App.java:258)
	at com.rarchives.ripme.App.handleArguments(App.java:228)
	at com.rarchives.ripme.App.main(App.java:67)
Caused by: org.jsoup.UnsupportedMimeTypeException: Unhandled content type. Must be text/*, application/xml, or application/xhtml+xml. Mimetype=image/gif, URL=https://thumbs.gfycat.com/BareDisloyalCleanerwrasse-size_restricted.gif
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:487)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	... 11 more`

**Comment by cyian-1756** [comment]
This is something that could be implemented per ripper, but I doubt it could be implmented generically without rewriting the logic for how rippers are chosen

**Comment by nfrelink** [comment]
Sorry for not replying back earlier. What I meant was that links like imgur.com/somename.gif or .gifv (particularly troublesome format imho) won't be ripped if they are a direct link. Like say.. if I have a Reddit post where I link the gif directly instead of the Imgur page it is on, it won't be able to rip it due to it being a direct link instead of HTML... Sorry if my explanation is bad

**Comment by DashLt** [comment]
Unsure why this was closed; I have a 58,000+ link text file, with a mix of direct links (i.imgur.com/xyz.png, i.redd.it/abc.png), and page links (imgur.com/a/bcd). RipMe fails to rip the direct links. Could this possibly get added/fixed?
