### ISSUE TITLE
Autorip fails on Linux due to URL having "\n" or null.

### ISSUE THREAD

**Issue by ParacosmPanda** [RipMeApp/ripme#752]
* Ripme version: 1.7.55
* Java version: openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10)
OpenJDK 64-Bit Server VM (build 10.0.1+10, mixed mode)

* Operating system: Linux DevPC 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux

* Exact URL you were trying to rip when the problem occurred:
(NSFW) http://boards.4chan.org/hr/thread/3153907

* Please include any additional information about how to reproduce the problem:
1. Under configuration enable (Autorip from Clipboard).
2. Start ripping any compatible URL.
3. Under Firefox while another rip is running, right click a link and select (Copy Link Location)
This will add it to the Queue.
4. When the last rip is finished and it goes to the clipboard copied URL it will say: "Unable to rip this URL: null".

## Expected Behavior

The URL should be sanitized and ripped normally.

## Actual Behavior

You get the: "Unable to rip this URL: null"
due to the fact that Linux (Arch and possibly others.) append a "\n" to the URL.

2018-06-28 17:18:45,609 DEBUG ripper.AbstractRipper .waitForThreads() Waiting for threads to finish
2018-06-28 17:18:45,609 INFO  ripper.AbstractRipper .checkIfComplete()    Rip completed!
2018-06-28 17:18:45,610 DEBUG ripper.AbstractRipper .checkIfComplete() Changing log file back to 'ripme.log'
2018-06-28 17:39:55,873 DEBUG ripper.DownloadThreadPool .initialize() Initializing Main thread pool with 5 threads
2018-06-28 17:39:55,877 ERROR ui.MainWindow .ripAlbum() [!] Error while ripping: null
java.lang.NullPointerException
	at com.rarchives.ripme.ui.MainWindow.ripAlbum(MainWindow.java:1144)
	at com.rarchives.ripme.ui.MainWindow.ripNextAlbum(MainWindow.java:1087)
	at com.rarchives.ripme.ui.MainWindow.access$600(MainWindow.java:67)
	at com.rarchives.ripme.ui.MainWindow$4.intervalAdded(MainWindow.java:852)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:153)
	at java.desktop/javax.swing.DefaultListModel.add(DefaultListModel.java:484)
	at com.rarchives.ripme.ui.MainWindow$RipButtonHandler.actionPerformed(MainWindow.java:1162)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:349)
	at com.rarchives.ripme.ui.MainWindow.ripAlbumStatic(MainWindow.java:1301)
	at com.rarchives.ripme.ui.AutoripThread.run(ClipboardUtils.java:77)

**Comment by cyian-1756** [comment]
Attempting this on Ubuntu 16.04 and everything works fine. I've checked both urls with and without newlines

**Comment by ParacosmPanda** [comment]
I'll post a video when I get a chance. I'll also check some other details such as other distros and different versions.

**Comment by ParacosmPanda** [comment]
After testing I was unable to reproduce this error again after it had happened for a full day even surviving reboots.
