### ISSUE TITLE
Error downloading an instagram tags page

### ISSUE THREAD

**Issue by m-r-k** [RipMeApp/ripme#769]
* Ripme version: 1.7.56
* Java version: openjdk version "1.8.0_171"
* Operating system: Linux Mint 18.3 Sylvia
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/explore/tags/dstgermany   and any other tags page

## Expected Behavior
Download the pics

## Actual Behavior
Error:
`Got exception while running ripper:
org.json.JSONException: JSONObject["data"] not found.
	at org.json.JSONObject.get(JSONObject.java:473)
	at org.json.JSONObject.getJSONObject(JSONObject.java:573)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getAfter(InstagramRipper.java:244)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getURLsFromJSON(InstagramRipper.java:253)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:58)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:555)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by tectomics** [comment]
It is correctly downloading the images, even though the URLs don't show anything.

I've tried logging in to see if it's my token being rate limited, as well as hopping between my actual IP and a few other across Europe.

**Comment by Isaaku** [comment]
This is working in 1.7.88. @cyian-1756 please close this
