### ISSUE TITLE
Errors continue after update, java.nio.file.NoSuchFileException and Can't rip this URL

### ISSUE THREAD

**Issue by louieDA** [RipMeApp/ripme#779]
* Ripme version: 1.7.57
* Java version: 
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

* Operating system: macos 10.13.5 (17F77)
* Exact URL you were trying to rip when the problem occurred: http://motherless.com/GEAA2662/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Rip album

## Actual Behavior

receiving error, more info attached. 

Any help is appreciated.

**Comment by louieDA** [comment]
Im not seeing what I attached so here's the terminal output

admin$ java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
admin$ java -jar ripme.jar
Loaded /Users/admin/Library/Application Support/ripme/rip.properties
Loaded log4j.properties
Initialized ripme v1.7.57
Setting locale to default
Error while loading jar file:
java.nio.file.NoSuchFileException: /Volumes/Seagate Backup  /Downloads/ripme.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:145)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1755)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1220)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:845)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:341)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:312)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:251)
	at com.rarchives.ripme.utils.Utils.getClassesForPackage(Utils.java:387)
	at com.rarchives.ripme.ripper.AbstractRipper.getRipperConstructors(AbstractRipper.java:518)
	at com.rarchives.ripme.ripper.AbstractRipper.getRipper(AbstractRipper.java:488)
	at com.rarchives.ripme.ui.MainWindow$2.update(MainWindow.java:626)
	at com.rarchives.ripme.ui.MainWindow$2.insertUpdate(MainWindow.java:610)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:203)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
	at java.desktop/javax.swing.text.PlainDocument.insertString(PlainDocument.java:131)
	at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:675)
	at java.desktop/javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1339)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$TextTransferHandler.handleReaderImport(BasicTextUI.java:2456)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$TextTransferHandler.importData(BasicTextUI.java:2596)
	at java.desktop/javax.swing.TransferHandler.importData(TransferHandler.java:827)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$TextTransferHandler.importData(BasicTextUI.java:2534)
	at java.desktop/javax.swing.TransferHandler$TransferAction.actionPerformedImpl(TransferHandler.java:1763)
	at java.desktop/javax.swing.TransferHandler$TransferAction.access$800(TransferHandler.java:1692)
	at java.desktop/javax.swing.TransferHandler$TransferAction$1.run(TransferHandler.java:1712)
	at java.desktop/javax.swing.TransferHandler$TransferAction$1.run(TransferHandler.java:1710)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/javax.swing.TransferHandler$TransferAction$2.run(TransferHandler.java:1727)
	at java.desktop/javax.swing.TransferHandler$TransferAction$2.run(TransferHandler.java:1725)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.TransferHandler$TransferAction.actionPerformed(TransferHandler.java:1724)
	at java.desktop/javax.swing.text.JTextComponent.invokeAction(JTextComponent.java:1523)
	at java.desktop/javax.swing.text.JTextComponent.paste(JTextComponent.java:1501)
	at java.desktop/javax.swing.text.DefaultEditorKit$PasteAction.actionPerformed(DefaultEditorKit.java:1374)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2948)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6366)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:871)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1140)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1010)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:836)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4847)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by louieDA** [comment]
![screen shot 2018-07-05 at 11 39 14 pm](https://user-images.githubusercontent.com/4048951/42360318-c17a49d0-80ad-11e8-867f-2f351276aa8f.png)


Here's a screen shot

**Comment by cyian-1756** [comment]
This looks to be a issues with Java finding the jar. Try moving it to a different dir and see it that fixes it

**Comment by louieDA** [comment]
Thank you so much! That was it, Ive been racking my brain for a week now.

**Comment by cyian-1756** [comment]
Does the path `/Volumes/Seagate Backup /Downloads/ripme.jar` not exist? I find it a bit strange that you can run the jar file but the jar file can't find its self

**Comment by cyian-1756** [comment]
> It does. Maybe the spaces in Seagate Backup?

Maybe but spaces in a file path haven't caused issues on any other OS to my knowledge. Unfortunately I can't really test this as Apple doesn't provide or support virtual machines and I don't own a mac. I'm going to close this issue as you've gotten ripme working again

**Comment by louieDA** [comment]
Thanks again.
