### ISSUE TITLE
Error attempting to rip any gallery on jabarchives.com

### ISSUE THREAD

**Issue by ectocooler** [RipMeApp/ripme#853]
* Ripme version: 1.7.60
* Java version:  Version 8 Update 181
* Operating system:  Version 1803 (OS Build 17134.165)

* Exact URL you were trying to rip when the problem occurred: https://www.jabarchives.com/main/view/mew_Toons
* Please include any additional information about how to reproduce the problem:
Ripme recognizes the URL as being valid, providing the green text, however when pressing "Rip" the below behavior occurs.

## Expected Behavior
Sucessful rip, initiated with the rip button is pressed.

## Actual Behavior
(It appears that the ripper is always expecting "albumname" to be present, when that actually changes depending on which album is being viewed)

2018-08-03 16:28:09,460 DEBUG ripper.AbstractRipper .getRipper() Found album ripper: com.rarchives.ripme.ripper.rippers.JabArchivesRipper
2018-08-03 16:28:10,596 DEBUG ripper.AbstractRipper .getRipper() Found album ripper: com.rarchives.ripme.ripper.rippers.JabArchivesRipper
2018-08-03 16:28:10,596 ERROR ui.MainWindow .ripAlbum() Could not find ripper for URL https://www.jabarchives.com/main/view/mew_Toons
java.net.MalformedURLException: Expected javarchives.com URL format: jabarchives.com/main/view/albumname - got https://www.jabarchives.com/main/view/mew_Toons instead
	at com.rarchives.ripme.ripper.rippers.JabArchivesRipper.getGID(JabArchivesRipper.java:42)
	at com.rarchives.ripme.ripper.AbstractRipper.getAlbumTitle(AbstractRipper.java:475)
	at com.rarchives.ripme.ripper.AlbumRipper.setWorkingDir(AlbumRipper.java:192)
	at com.rarchives.ripme.ripper.AbstractRipper.setup(AbstractRipper.java:178)
	at com.rarchives.ripme.ui.MainWindow.ripAlbum(MainWindow.java:1128)
	at com.rarchives.ripme.ui.MainWindow.ripNextAlbum(MainWindow.java:1087)
	at com.rarchives.ripme.ui.MainWindow.access$600(MainWindow.java:67)
	at com.rarchives.ripme.ui.MainWindow$4.intervalAdded(MainWindow.java:852)
	at javax.swing.AbstractListModel.fireIntervalAdded(Unknown Source)
	at javax.swing.DefaultListModel.add(Unknown Source)
	at com.rarchives.ripme.ui.MainWindow$RipButtonHandler.actionPerformed(MainWindow.java:1162)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by cyian-1756** [comment]
Looks like it doesn't like the www. in the url.
