### ISSUE TITLE
Ripme fails to download from gfycat (through reddit)

### ISSUE THREAD

**Issue by itchoi09** [RipMeApp/ripme#876]
* Ripme version: 1.7.62 
* Java version: 
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

* Operating system: 
windows 7 ultimate version 6.1

* Exact URL you were trying to rip when the problem occurred: 
Reddit links , havn't checked others. Sorry
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Ripme should have donwnloaded all the mp4 files from imgur, v.reddit, gyfcat etc. 
## Actual Behavior
Ripme only downloads from imgur and v.reddit. None from gyfcat. 

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.
this is from the log.txt

2018-08-24 04:20:00,116 WARN  utils.RipUtils .getFilesFromURL() Exception while retrieving gfycat page:
java.io.IOException: Could not find source#mp4source at https://gfycat.com/EnviousCommonGraysquirrel
	at com.rarchives.ripme.ripper.rippers.GfycatRipper.getVideoURL(GfycatRipper.java:100)
	at com.rarchives.ripme.utils.RipUtils.getFilesFromURL(RipUtils.java:70)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.handleURL(RedditRipper.java:238)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.parseJsonChild(RedditRipper.java:170)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.getAndParseAndReturnNext(RedditRipper.java:102)
	at com.rarchives.ripme.ripper.rippers.RedditRipper.rip(RedditRipper.java:77)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:556)
	at java.lang.Thread.run(Unknown Source)

**Comment by cyian-1756** [comment]
Looks gfycat changed their html, I'll get on fixing it

**Comment by cyian-1756** [comment]
This is fixed in 1.7.63

**Comment by itchoi09** [comment]
Thank you so much for your quick and hard work. Really appreciate everything.
