### ISSUE TITLE
hentai.cafe not working correctly

### ISSUE THREAD

**Issue by wankio** [RipMeApp/ripme#908]
Today when i test it again

https://hentai.cafe/momi-flappy-sugar-babies/ 
downloaded 141/204  then it say "Rip complete"

``2018-09-05 22:30:21,190 DEBUG ripper.AbstractRipper .rip() Found image url #56: https://cdn.hentai.cafe/manga/content/comics/momi-flappy-sugar-babies_5b8d39142fbe7/1-0_5b8d393fe4a4f/056.jpg
2018-09-05 22:30:28,217 WARN  utils.Http .response() Error while loading https://hentai.cafe/manga/read/momi-flappy-sugar-babies/en/0/1/page/57
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:453)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:434)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:181)
	at com.rarchives.ripme.utils.Http.response(Http.java:130)
	at com.rarchives.ripme.utils.Http.get(Http.java:110)
	at com.rarchives.ripme.ripper.rippers.HentaiCafeRipper.getNextPage(HentaiCafeRipper.java:57)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:165)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:556)
	at java.lang.Thread.run(Unknown Source)
2018-09-05 22:30:28,217 INFO  ripper.AbstractRipper .rip() Can't get next page: Failed to load https://hentai.cafe/manga/read/momi-flappy-sugar-babies/en/0/1/page/57 after 1 attempts
2018-09-05 22:30:28,218 DEBUG ripper.AbstractRipper .waitForThreads() Waiting for threads to finish
2018-09-05 22:30:28,218 INFO  ripper.AbstractRipper .checkIfComplete()    Rip completed!
2018-09-05 22:30:28,218 DEBUG ripper.AbstractRipper .checkIfComplete() Changing log file back to 'ripme.log'
``

**Comment by cyian-1756** [comment]
That looks like a network error on your end. Have you tried ripping it again?

**Comment by wankio** [comment]
yes, rip again, i just tested with jdownloader 2, 204 images downloaded without any problem

**Comment by cyian-1756** [comment]
> yes, rip again

If it's working then I'm going to close this issue
